#!/usr/bin/env bash
# Proves the shared verification snapshot contains exactly the current
# tracked/non-ignored candidate files and never copies Git metadata or ignores.
set -euo pipefail
cd "$(dirname "$0")/../.."
root="$PWD"

materializer="scripts/ci/materialize-public-candidate-tree.sh"
test_root="$(mktemp -d)"
cleanup() {
  case "${test_root:-}" in
    /tmp/*|/var/tmp/*|[A-Za-z]:/*) [ ! -e "$test_root" ] || rm -rf -- "$test_root" ;;
    *) echo "public-tree-snapshot-self-test: refusing unsafe cleanup" >&2 ;;
  esac
}
trap cleanup EXIT

source_repo="$test_root/source"
snapshot="$test_root/snapshot"
mkdir -p "$source_repo"
git -C "$source_repo" init --quiet
git -C "$source_repo" config user.name Synthetic
git -C "$source_repo" config user.email synthetic@example.invalid
cp -- "$root/.gitignore" "$source_repo/.gitignore"
printf '\nignored.txt\n' >>"$source_repo/.gitignore"
printf 'tracked\n' >"$source_repo/tracked.txt"
git -C "$source_repo" add .gitignore tracked.txt
git -C "$source_repo" commit --quiet -m synthetic
printf 'working tree\n' >"$source_repo/tracked.txt"
printf 'new candidate\n' >"$source_repo/untracked.txt"
printf 'must stay private\n' >"$source_repo/ignored.txt"
mkdir -p "$source_repo/.pnpm-store/v3/files"
printf 'generated cache\n' >"$source_repo/.pnpm-store/v3/files/cache-entry"
mkdir -p "$source_repo/scripts/guard/__pycache__"
printf 'generated bytecode\n' >"$source_repo/scripts/guard/__pycache__/guard.cpython-312.pyc"
printf 'generated bytecode\n' >"$source_repo/generated.pyo"

if [ ! -x "$materializer" ]; then
  echo "FAIL public-tree-snapshot-self-test: missing executable materializer" >&2
  exit 1
fi
"$materializer" "$source_repo" "$snapshot"

if [ "$(cat "$snapshot/tracked.txt")" != "working tree" ] \
  || [ "$(cat "$snapshot/untracked.txt")" != "new candidate" ] \
  || [ -e "$snapshot/ignored.txt" ] \
  || [ -e "$snapshot/.pnpm-store" ] \
  || [ -e "$snapshot/scripts/guard/__pycache__" ] \
  || [ -e "$snapshot/generated.pyo" ] \
  || [ -e "$snapshot/.git" ]; then
  echo "FAIL public-tree-snapshot-self-test: candidate-set isolation drift" >&2
  exit 1
fi

poison_index="$test_root/poison.index"
GIT_INDEX_FILE="$poison_index" git -C "$source_repo" read-tree --empty
GIT_INDEX_FILE="$poison_index" git -C "$source_repo" add -f ignored.txt
poison_config="$test_root/poison.gitconfig"
git config --file "$poison_config" core.fsmonitor '!touch should-not-run'
ambient_snapshot="$test_root/ambient-snapshot"
GIT_INDEX_FILE="$poison_index" \
GIT_OBJECT_DIRECTORY="$test_root/missing-objects" \
GIT_CONFIG_GLOBAL="$poison_config" \
  "$materializer" "$source_repo" "$ambient_snapshot" >/dev/null
if [ -e "$ambient_snapshot/ignored.txt" ]; then
  echo "FAIL public-tree-snapshot-self-test: inherited a caller-controlled Git index" >&2
  exit 1
fi

trusted_snapshot="$test_root/trusted-snapshot"
PERFECTORY_TRUSTED_GIT_INDEX_FILE="$poison_index" \
  "$materializer" "$source_repo" "$trusted_snapshot" >/dev/null
if [ "$(cat "$trusted_snapshot/ignored.txt")" != "must stay private" ]; then
  echo "FAIL public-tree-snapshot-self-test: explicit trusted index was not materialized" >&2
  exit 1
fi

printf 'occupied\n' >"$test_root/occupied"
if "$materializer" "$source_repo" "$test_root" >/dev/null 2>&1; then
  echo "FAIL public-tree-snapshot-self-test: accepted non-empty destination" >&2
  exit 1
fi

# The one-time publisher rejects symlinks before the public root is created,
# but every later public PR is protected by the persistent repository guard.
# Exercise that real guard against a small synthetic tracked tree so a generic
# guard failure cannot hide acceptance of a mode-120000 entry.
guard_repo="$test_root/persistent-guard"
mkdir -p \
  "$guard_repo/scripts/guard" \
  "$guard_repo/tools/github" \
  "$guard_repo/LICENSES" \
  "$guard_repo/products/gongzzang/apps/web/public/fonts"
cp -- "$root/scripts/guard/public-repository-safety.sh" \
  "$guard_repo/scripts/guard/public-repository-safety.sh"
cp -- "$root/.gitattributes" "$guard_repo/.gitattributes"
for stub in \
  check-tracked-blob-sizes.sh \
  public-fixture-safety.sh \
  public-doc-boundary.sh \
  check-workflow-policy.sh; do
  printf '#!/usr/bin/env bash\nexit 0\n' >"$guard_repo/scripts/guard/$stub"
done
printf '#!/usr/bin/env python3\nraise SystemExit(0)\n' \
  >"$guard_repo/scripts/guard/check-package-publication-policy.py"
for required in \
  LICENSE \
  LICENSES/LicenseRef-Proprietary.txt \
  LICENSES/OFL-1.1.txt \
  REUSE.toml \
  THIRD_PARTY_NOTICES.md \
  CONTRIBUTING.md \
  products/gongzzang/apps/web/public/fonts/LICENSE-PRETENDARD.txt; do
  printf 'synthetic public-safety fixture\n' >"$guard_repo/$required"
done
printf '{"version":1,"artifacts":{}}\n' \
  >"$guard_repo/tools/github/third-party-artifact-policy.json"
font_dir="$guard_repo/products/gongzzang/apps/web/public/fonts"
printf 'synthetic font\n' >"$font_dir/synthetic.woff2"
printf '/* synthetic font stylesheet */\n' \
  >"$font_dir/pretendardvariable-dynamic-subset.css"
font_hash="$(sha256sum "$font_dir/synthetic.woff2" | awk '{ print $1 }')"
printf '%s *synthetic.woff2\n' "$font_hash" \
  >"$font_dir/pretendard-v1.3.9.sha256"
image_digest="$(printf '0%.0s' {1..64})"
for image_name in \
  RUST_TOOLCHAIN_IMAGE \
  NODE_VERIFY_IMAGE \
  LYCHEE_IMAGE \
  REUSE_IMAGE; do
  printf '%s=example.invalid/synthetic:1@sha256:%s\n' \
    "$image_name" "$image_digest" >>"$guard_repo/tools/container-images.env"
done

git -C "$guard_repo" init --quiet
git -C "$guard_repo" add .
while IFS= read -r script_path; do
  git -C "$guard_repo" update-index --chmod=+x -- "$script_path"
done < <(git -C "$guard_repo" ls-files 'scripts/**')
link_blob="$(printf '../private-evidence\n' \
  | git -C "$guard_repo" hash-object -w --stdin)"
git -C "$guard_repo" update-index --add --cacheinfo \
  "120000,$link_blob,synthetic-tracked-symlink"

set +e
symlink_output="$(
  cd "$guard_repo"
  bash scripts/guard/public-repository-safety.sh 2>&1
)"
symlink_status=$?
set -e
if [ "$symlink_status" -eq 0 ] \
  || ! printf '%s\n' "$symlink_output" \
    | grep -Fq '120000 synthetic-tracked-symlink'; then
  echo "FAIL public-tree-snapshot-self-test: persistent guard accepted a tracked mode-120000 symlink" >&2
  printf '%s\n' "$symlink_output" >&2
  exit 1
fi

git -C "$guard_repo" update-index --force-remove -- synthetic-tracked-symlink
non_executable_script="scripts/guard/public-doc-boundary.sh"
git -C "$guard_repo" update-index --chmod=-x -- "$non_executable_script"
set +e
mode_output="$(
  cd "$guard_repo"
  bash scripts/guard/public-repository-safety.sh 2>&1
)"
mode_status=$?
set -e
if [ "$mode_status" -eq 0 ] \
  || ! printf '%s\n' "$mode_output" \
    | grep -Fq "100644 $non_executable_script"; then
  echo "FAIL public-tree-snapshot-self-test: persistent guard accepted a non-executable tracked shebang script" >&2
  printf '%s\n' "$mode_output" >&2
  exit 1
fi

echo "OK public-tree-snapshot-self-test"
