#!/usr/bin/env bash
set -euo pipefail

root="$(cd "$(dirname "$0")/../.." && pwd -P)"
checker="$root/scripts/guard/r2-env-namespace-consistency.sh"
fixture="$(mktemp -d)"
trap 'rm -rf "$fixture"' EXIT

mkdir -p "$fixture/platforms/foundation-platform/config" "$fixture/scripts"
cat > "$fixture/platforms/foundation-platform/.env.example" <<'EOF'
FOUNDATION_PLATFORM_R2_LAKEHOUSE_ACCOUNT_ID=
FOUNDATION_PLATFORM_R2_LAKEHOUSE_ENDPOINT=
FOUNDATION_PLATFORM_R2_LAKEHOUSE_BUCKET=
FOUNDATION_PLATFORM_R2_LAKEHOUSE_REGION=auto
FOUNDATION_PLATFORM_R2_LAKEHOUSE_RUNTIME_ACCESS_KEY_ID=
FOUNDATION_PLATFORM_R2_LAKEHOUSE_RUNTIME_SECRET_ACCESS_KEY=
FOUNDATION_PLATFORM_R2_LAKEHOUSE_PUBLIC_BASE_URL=
FOUNDATION_PLATFORM_R2_TILE_DERIVATIVES_ACCOUNT_ID=
FOUNDATION_PLATFORM_R2_TILE_DERIVATIVES_ENDPOINT=
FOUNDATION_PLATFORM_R2_TILE_DERIVATIVES_BUCKET=
FOUNDATION_PLATFORM_R2_TILE_DERIVATIVES_REGION=auto
FOUNDATION_PLATFORM_R2_TILE_DERIVATIVES_PREFIX=gold/vector-tiles/releases
FOUNDATION_PLATFORM_R2_TILE_DERIVATIVES_PUBLISHER_ACCESS_KEY_ID=
FOUNDATION_PLATFORM_R2_TILE_DERIVATIVES_PUBLISHER_SECRET_ACCESS_KEY=
FOUNDATION_PLATFORM_R2_TILE_DERIVATIVES_MARTIN_READ_ACCESS_KEY_ID=
FOUNDATION_PLATFORM_R2_TILE_DERIVATIVES_MARTIN_READ_SECRET_ACCESS_KEY=
FOUNDATION_PLATFORM_R2_POSTGRES_RECOVERY_BUCKET=
FOUNDATION_PLATFORM_R2_POSTGRES_RECOVERY_ENDPOINT_HOST=
FOUNDATION_PLATFORM_R2_POSTGRES_RECOVERY_BACKUP_ACCESS_KEY_ID=
FOUNDATION_PLATFORM_R2_POSTGRES_RECOVERY_BACKUP_SECRET_ACCESS_KEY=
EOF
{
  printf '{\n  "canonical_keys": [\n'
  for key in \
    FOUNDATION_PLATFORM_R2_LAKEHOUSE_ACCOUNT_ID \
    FOUNDATION_PLATFORM_R2_LAKEHOUSE_ENDPOINT \
    FOUNDATION_PLATFORM_R2_LAKEHOUSE_BUCKET \
    FOUNDATION_PLATFORM_R2_LAKEHOUSE_REGION \
    FOUNDATION_PLATFORM_R2_LAKEHOUSE_RUNTIME_ACCESS_KEY_ID \
    FOUNDATION_PLATFORM_R2_LAKEHOUSE_RUNTIME_SECRET_ACCESS_KEY \
    FOUNDATION_PLATFORM_R2_LAKEHOUSE_PUBLIC_BASE_URL \
    FOUNDATION_PLATFORM_R2_TILE_DERIVATIVES_ACCOUNT_ID \
    FOUNDATION_PLATFORM_R2_TILE_DERIVATIVES_ENDPOINT \
    FOUNDATION_PLATFORM_R2_TILE_DERIVATIVES_BUCKET \
    FOUNDATION_PLATFORM_R2_TILE_DERIVATIVES_REGION \
    FOUNDATION_PLATFORM_R2_TILE_DERIVATIVES_PREFIX \
    FOUNDATION_PLATFORM_R2_TILE_DERIVATIVES_PUBLISHER_ACCESS_KEY_ID \
    FOUNDATION_PLATFORM_R2_TILE_DERIVATIVES_PUBLISHER_SECRET_ACCESS_KEY \
    FOUNDATION_PLATFORM_R2_TILE_DERIVATIVES_MARTIN_READ_ACCESS_KEY_ID \
    FOUNDATION_PLATFORM_R2_TILE_DERIVATIVES_MARTIN_READ_SECRET_ACCESS_KEY \
    FOUNDATION_PLATFORM_R2_POSTGRES_RECOVERY_BUCKET \
    FOUNDATION_PLATFORM_R2_POSTGRES_RECOVERY_ENDPOINT_HOST \
    FOUNDATION_PLATFORM_R2_POSTGRES_RECOVERY_BACKUP_ACCESS_KEY_ID \
    FOUNDATION_PLATFORM_R2_POSTGRES_RECOVERY_BACKUP_SECRET_ACCESS_KEY; do
    printf '    "%s",\n' "$key"
  done
  printf '    "sentinel"\n  ]\n}\n'
} > "$fixture/platforms/foundation-platform/config/r2-connections.contract.json"
printf '%s\n' 'R2_MODE=false' > "$fixture/scripts/internal.sh"

git -C "$fixture" init -q
git -C "$fixture" config user.email guard@example.invalid
git -C "$fixture" config user.name guard
git -C "$fixture" add .
bash "$checker" "$fixture" >/dev/null

printf '%s\n' 'R2_BUCKET_NAME=legacy' > "$fixture/platforms/foundation-platform/.env.local"
if bash "$checker" "$fixture" >/dev/null 2>&1; then
  echo 'FAIL r2-env-namespace-consistency-self-test: stale local key was accepted' >&2
  exit 1
fi
rm -f "$fixture/platforms/foundation-platform/.env.local"

printf '%s\n' 'R2_BUCKET_NAME=legacy' >> "$fixture/scripts/internal.sh"
git -C "$fixture" add .
if bash "$checker" "$fixture" >/dev/null 2>&1; then
  echo 'FAIL r2-env-namespace-consistency-self-test: legacy assignment was accepted' >&2
  exit 1
fi

echo 'OK r2-env-namespace-consistency-self-test'
