#!/usr/bin/env bash
set -Eeuo pipefail
umask 022

# Independent root-owned control checkout, not code taken from the candidate archive (root
# ADR-0134 §1). No environment override: a caller cannot appoint the verifier that admits it.
admission="/opt/perfectory-control/current/scripts/deploy/foundation-release-admission.py"
# The one path sudo may run this script from (root ADR-0134 §2). A wildcard over release
# directories also matches a release that was never admitted.
control_release_script="/opt/perfectory-control/current/platforms/foundation-platform/scripts/deploy/foundation-release.sh"
# What survives `prune` is read from the control checkout too, for the same reason: a release
# cannot choose what survives it. The emergency release is named there and nowhere else.
retention_contract="/opt/perfectory-control/current/tools/release-retention.contract.json"
control_releases_dir="/opt/perfectory-control/releases"

release_root="${FOUNDATION_PLATFORM_RELEASE_ROOT:-/opt/foundation-platform}"
state_root="${FOUNDATION_PLATFORM_STATE_ROOT:-/var/lib/foundation-platform}"
releases_dir="${release_root}/releases"
# Mutable inputs live beside the immutable releases, keyed by release id (root ADR-0134 §3):
# the trusted build output under artifacts/<sha>/, operator configuration under config/<sha>/.
config_dir="${release_root}/config"
lakehouse_uid="${FOUNDATION_PLATFORM_LAKEHOUSE_UID:-185}"
lakehouse_gid="${FOUNDATION_PLATFORM_LAKEHOUSE_GID:-185}"

usage() {
  cat >&2 <<'USAGE'
usage:
  foundation-release.sh prepare <40-char-git-sha> <source.tar.gz>
  foundation-release.sh floor-config <40-char-git-sha> <non-secret-env-file>
  foundation-release.sh install <40-char-git-sha> <source.tar.gz>
  foundation-release.sh activate <40-char-git-sha>
  foundation-release.sh migrate
  foundation-release.sh verify
  foundation-release.sh timers [<airflow-scheduler-ssh-public-key-file>]
  foundation-release.sh rollback
  foundation-release.sh prune
  foundation-release.sh deployer-access <account> [--exclusive]
  foundation-release.sh status
USAGE
  exit 64
}

require_release_id() {
  local release_id="$1"
  [[ "${release_id}" =~ ^[0-9a-f]{40}$ ]] || {
    printf 'release id must be a lowercase 40-character Git SHA: %s\n' "${release_id}" >&2
    exit 64
  }
}

release_path() {
  printf '%s/%s' "${releases_dir}" "$1"
}

# Airflow's only way onto this host (root ADR-0122 §2): an account that cannot log in, whose one
# SSH key runs one command, which may start and stop exactly the services of enabled jobs. All of
# it is rebuilt from the release on every `timers`, so a job switched on or off changes it too.
scheduler_account=foundation-scheduler
scheduler_home=/var/lib/foundation-scheduler

install_scheduler_access() {
  local jobs_file="$1" public_key_file="$2" key subnet sudoers staged
  if ! id "${scheduler_account}" >/dev/null 2>&1; then
    useradd --system --home-dir "${scheduler_home}" --create-home --shell /bin/bash \
      --groups systemd-journal "${scheduler_account}"
    # No password and not locked: sshd still accepts its key, nothing accepts a password.
    usermod -p '*' "${scheduler_account}"
  fi
  install -d -o "${scheduler_account}" -g "${scheduler_account}" -m 0700 "${scheduler_home}/.ssh"
  if [[ -n "${public_key_file}" ]]; then
    key="$(cat "${public_key_file}")"
    [[ "${key}" =~ ^ssh-ed25519\ [A-Za-z0-9+/=]+(\ [A-Za-z0-9@._-]+)?$ ]] || {
      printf 'scheduler key must be one ssh-ed25519 public key line: %s\n' "${public_key_file}" >&2
      exit 65
    }
    # The key works only from the scheduler's own network, read from Docker rather than written
    # down: start Airflow (airflow-runtime.sh up -d) before installing it.
    subnet="$(docker network inspect airflow_default \
      -f '{{range .IPAM.Config}}{{.Subnet}} {{end}}' 2>/dev/null | awk '{print $1}')"
    [[ "${subnet}" =~ ^[0-9]{1,3}(\.[0-9]{1,3}){3}/[0-9]{1,2}$ ]] || {
      printf 'the airflow_default network is missing; run airflow-runtime.sh up -d first\n' >&2
      exit 69
    }
    # No pty, forwarding or agent; the command is fixed whatever the client asks for.
    printf 'restrict,from="%s",command="%s/current/scripts/ops/start-scheduled-job.sh" %s\n' \
      "${subnet}" "${release_root}" "${key}" >"${scheduler_home}/.ssh/authorized_keys"
    chown "${scheduler_account}:${scheduler_account}" "${scheduler_home}/.ssh/authorized_keys"
    chmod 0600 "${scheduler_home}/.ssh/authorized_keys"
  fi
  # Exact command lines, one start and one stop per enabled job's service; nothing else.
  staged="$(mktemp)"
  python3 - "${jobs_file}" "${scheduler_account}" >"${staged}" <<'PY'
import json, re, sys
jobs, account = sys.argv[1], sys.argv[2]
print("# Generated by foundation-release.sh timers from orchestration/jobs.v1.json (root ADR-0122).")
for job in json.load(open(jobs))["jobs"]:
    service = job["systemd_service"]
    if not re.fullmatch(r"foundation-[a-z0-9-]+(@[a-z0-9-]+)?\.service", service):
        sys.exit(f"refusing service name {service!r}")
    if job["enabled"]:
        print(f"{account} ALL=(root) NOPASSWD: /usr/bin/systemctl start --no-block {service}, "
              f"/usr/bin/systemctl stop {service}")
PY
  sudoers=/etc/sudoers.d/foundation-scheduler
  visudo -cqf "${staged}" || {
    rm -f "${staged}"
    printf 'generated sudoers did not validate; %s left unchanged\n' "${sudoers}" >&2
    exit 65
  }
  install -o root -g root -m 0440 "${staged}" "${sudoers}"
  rm -f "${staged}"
  printf 'scheduler-access-ok account=%s key=%s\n' "${scheduler_account}" \
    "$([[ -s "${scheduler_home}/.ssh/authorized_keys" ]] && echo installed || echo missing)"
}

prepare_mutable_state() {
  local directory
  [[ "${lakehouse_uid}" =~ ^[0-9]+$ && "${lakehouse_gid}" =~ ^[0-9]+$ ]] || {
    printf 'lakehouse uid and gid must be numeric\n' >&2
    exit 64
  }
  for directory in "${state_root}/lakehouse" "${state_root}/remote-lakehouse"; do
    mkdir -p "${directory}"
    if [[ "$(id -u)" -eq 0 ]]; then
      chown "${lakehouse_uid}:${lakehouse_gid}" "${directory}"
    fi
    chmod 0770 "${directory}"
    [[ -w "${directory}" || "$(id -u)" -eq 0 ]] || {
      printf 'mutable state directory is not writable: %s\n' "${directory}" >&2
      exit 73
    }
  done
}

atomic_link() {
  local target="$1"
  local link_path="$2"
  local pending="${link_path}.next.$$"
  ln -s "${target}" "${pending}"
  mv -Tf "${pending}" "${link_path}"
}

assert_installed_release() {
  local release_id="$1"
  local path
  path="$(release_path "${release_id}")"
  [[ -d "${path}" ]] || {
    printf 'release is not installed: %s\n' "${release_id}" >&2
    exit 66
  }
  [[ "$(cat "${path}/.foundation-release-id")" == "${release_id}" ]] || {
    printf 'release identity evidence is missing or invalid: %s\n' "${path}" >&2
    exit 65
  }
  # Canonical-main ancestry and every installed byte, read again; the marker above is a name.
  "${admission}" verify "${path}"
}

assert_current_release() {
  local current_target
  current_target="$(readlink "${release_root}/current")"
  [[ "${current_target}" =~ ^releases/([0-9a-f]{40})$ ]] || {
    printf 'current is not an installed release link\n' >&2
    exit 65
  }
  assert_installed_release "${BASH_REMATCH[1]}"
}

# The drop-in goes on the unit systemd actually loads for the service. For a template instance
# that is the template, so an instance nobody registered (started by hand) is checked too.
admission_dropin_unit() {
  local service="$1"
  [[ "${service}" =~ ^(foundation-[a-z0-9-]+)(@[a-z0-9-]*)?\.service$ ]] || {
    printf 'refusing invalid service name for release admission: %s\n' "${service}" >&2
    return 65
  }
  if [[ -n "${BASH_REMATCH[2]}" ]]; then
    printf '%s@.service\n' "${BASH_REMATCH[1]}"
  else
    printf '%s.service\n' "${BASH_REMATCH[1]}"
  fi
}

install_release_admission() {
  local unit
  unit="$(admission_dropin_unit "$1")" || exit 65
  install -d -o root -g root -m 0755 "/etc/systemd/system/${unit}.d"
  install -o root -g root -m 0644 \
    "${release_root}/current/infra/systemd/foundation-release-admission.conf" \
    "/etc/systemd/system/${unit}.d/10-release-admission.conf"
}

# sudo's grant for this script names the control checkout's copy and nothing else (root
# ADR-0134 §2). The rule this replaces, /opt/foundation-platform/*/scripts/deploy/..., matched
# every directory under the release root, including a release that was never admitted.
render_deployer_sudoers() {
  local account="$1"
  [[ "${account}" =~ ^[a-z_][a-z0-9_-]{0,31}$ ]] || {
    printf 'deployer account must be a plain user name: %s\n' "${account}" >&2
    return 64
  }
  printf '# Generated by foundation-release.sh deployer-access (root ADR-0134 §2).\n'
  printf '%s ALL=(root) NOPASSWD: %s\n' "${account}" "${control_release_script}"
}

# Prints every sudoers line that still grants this script by any other path. Exit 0 only when
# none does: an old wildcard left beside the exact rule keeps the unadmitted path open.
find_other_release_grants() {
  local found=0 file
  for file in "$@"; do
    [[ -f "${file}" ]] || continue
    # Rule lines only: a comment that names this script grants nothing. The exact control path is
    # removed before looking, so a second path on the same line as it is still reported.
    if grep -HnE '^[[:space:]]*[^#[:space:]].*foundation-release\.sh' "${file}" |
      sed "s|${control_release_script}||g" | grep -E 'foundation-release\.sh'; then
      found=1
    fi
  done
  return "${found}"
}

# Two steps, in this order (root ADR-0134 §2): `deployer-access <account>` installs the exact rule
# and lists any older grant still present, which keeps working until it is deleted; after the new
# path has been used successfully, the old line is deleted and `deployer-access <account>
# --exclusive` fails while any other grant remains.
install_deployer_access() {
  local account="$1" mode="${2:-}" staged sudoers=/etc/sudoers.d/foundation-release
  [[ -z "${mode}" || "${mode}" == --exclusive ]] || usage
  id "${account}" >/dev/null 2>&1 || {
    printf 'deployer account does not exist: %s\n' "${account}" >&2
    exit 67
  }
  staged="$(mktemp)"
  render_deployer_sudoers "${account}" >"${staged}" || { rm -f "${staged}"; exit 64; }
  visudo -cqf "${staged}" || {
    rm -f "${staged}"
    printf 'generated sudoers did not validate; %s left unchanged\n' "${sudoers}" >&2
    exit 65
  }
  install -o root -g root -m 0440 "${staged}" "${sudoers}"
  rm -f "${staged}"
  deployer_grant_verdict "${account}" "${mode}" /etc/sudoers /etc/sudoers.d/* || exit 65
}

deployer_grant_verdict() {
  local account="$1" mode="$2"; shift 2
  if ! find_other_release_grants "$@"; then
    if [[ "${mode}" == --exclusive ]]; then
      printf 'another sudoers rule still grants this script; delete it (runbook: release admission)\n' >&2
      return 65
    fi
    printf 'deployer-access-installed account=%s; the grants listed above remain until deleted\n' "${account}"
    return 0
  fi
  printf 'deployer-access-ok account=%s command=%s\n' "${account}" "${control_release_script}"
}

activate_release() {
  local release_id="$1"
  local next_target="releases/${release_id}"
  local current_target=""
  assert_installed_release "${release_id}"

  if [[ -L "${release_root}/current" ]]; then
    current_target="$(readlink "${release_root}/current")"
  elif [[ -e "${release_root}/current" ]]; then
    printf 'current exists but is not a symbolic link\n' >&2
    exit 65
  fi

  # Compare the two existing contracts, not a second capability registry. A release predating
  # orchestration has nothing to preserve; removing an enabled job requires an explicit false
  # entry first. The dedicated rollback command intentionally bypasses this admission gate.
  python3 - "${release_root}/current/orchestration/jobs.v1.json" \
    "$(release_path "${release_id}")/orchestration/jobs.v1.json" <<'PY'
import json, pathlib, sys

def jobs(path):
    if not path.exists():
        if path.is_symlink():
            raise ValueError('dangling jobs contract')
        return {}
    raw = json.loads(path.read_text(encoding='utf-8'))
    if not isinstance(raw, dict) or not isinstance(raw.get('jobs'), list):
        raise ValueError('jobs contract must contain a jobs array')
    result = {}
    for job in raw['jobs']:
        if (not isinstance(job, dict) or not isinstance(job.get('id'), str) or
            not job['id'] or type(job.get('enabled')) is not bool or job['id'] in result):
            raise ValueError('invalid or duplicate job identity/enabled value')
        result[job['id']] = job['enabled']
    return result

try:
    previous, candidate = map(jobs, map(pathlib.Path, sys.argv[1:]))
    missing = sorted(name for name, enabled in previous.items() if enabled and name not in candidate)
    if missing:
        raise ValueError('candidate removes enabled jobs; retain explicit enabled:false entries: ' + ', '.join(missing))
except (OSError, ValueError) as error:
    sys.exit('release activation refused: ' + str(error))
PY

  if [[ -n "${current_target}" && "${current_target}" != "${next_target}" ]]; then
    atomic_link "${current_target}" "${release_root}/previous"
  fi
  atomic_link "${next_target}" "${release_root}/current"
}

# A release is a tree rooted at platforms/foundation-platform, and this is where that is
# enforced — before anything is staged or activated. On 2026-09-03 an archive of the monorepo
# root installed, activated, and only then failed the schema check because scripts/deploy/ was
# a level deeper than every path this script derives. By that point the release id was sealed
# to the wrong archive's sha256 and could never be installed correctly again. The marker asked
# for is this script's own runtime schema check: the thing `install` will need to run last.
validate_archive_is_a_release() {
  local archive="$1" listing
  # The listing is captured, not piped into the match. Piped, `grep -q` exits on its first hit
  # and closes the pipe; tar dies of SIGPIPE (141), and under `pipefail` the pipeline fails even
  # though the file was found — so this gate refused every valid archive large enough for tar to
  # still be writing when grep matched. That is exactly what happened on 2026-09-03: the first
  # real deployment after this gate merged was refused with the "not a release tree" message,
  # while the same grep run by hand on the same archive counted one match. The single-file
  # rehearsal fixture never triggered it, because tar had already finished. A verdict must never
  # sit downstream of a pipe whose producer can be killed by the verdict being reached.
  listing="$(tar -tzf "${archive}")"
  grep -qE '^(\./)?scripts/deploy/assert-runtime-migrations\.sh$' <<<"${listing}" || {
    printf 'archive is not a release tree: scripts/deploy/assert-runtime-migrations.sh is not at its root\n' >&2
    printf 'archive the subtree, not the monorepo: git archive "<sha>:platforms/foundation-platform"\n' >&2
    exit 65
  }
}

validate_archive_paths() {
  local archive="$1"
  local entry normalized
  while IFS= read -r entry; do
    normalized="${entry#./}"
    [[ -z "${normalized}" || "${normalized}" == "." ]] && continue
    if [[ "${normalized}" == /* || "${normalized}" =~ (^|/)\.\.(/|$) ]]; then
      printf 'archive contains unsafe path: %s\n' "${entry}" >&2
      exit 65
    fi
  done < <(tar -tzf "${archive}")
}

install_release() {
  local release_id="$1"
  local archive="$2"
  local activate="${3:-yes}"
  local target archive_sha recorded_sha staging=""
  require_release_id "${release_id}"
  [[ -f "${archive}" ]] || {
    printf 'release archive does not exist: %s\n' "${archive}" >&2
    exit 66
  }
  validate_archive_paths "${archive}"
  validate_archive_is_a_release "${archive}"
  archive_sha="$(sha256sum "${archive}" | awk '{print $1}')"
  target="$(release_path "${release_id}")"

  mkdir -p "${releases_dir}" "${state_root}/recovery"
  prepare_mutable_state
  if [[ -e "${target}" ]]; then
    "${admission}" build "${target}"
    assert_installed_release "${release_id}"
    recorded_sha="$(cat "${target}/.foundation-release-archive-sha256")"
    [[ "${recorded_sha}" == "${archive_sha}" ]] || {
      printf 'release id already exists with a different archive: %s\n' "${release_id}" >&2
      exit 65
    }
    if [[ "${activate}" == yes ]]; then activate_and_prune "${release_id}"; fi
    return
  fi

  staging="$(mktemp -d "${releases_dir}/.${release_id}.tmp.XXXXXX")"
  trap '[[ -z "${staging:-}" ]] || { chmod -R u+w "${staging}"; rm -rf "${staging}"; }' RETURN
  # Admission fetches canonical main, checks ancestry AND the complete archive contents, then
  # writes read-only files from those Git objects. The supplied tar is never extracted.
  "${admission}" prepare "${release_id}" "${archive}" "${staging}"
  mv "${staging}" "${target}"
  staging=""
  trap - RETURN
  # The publisher and Spark jars are built from the admitted tree into artifacts/<sha>/, never
  # accepted from the caller and never written inside the release.
  "${admission}" build "${target}"
  if [[ "${activate}" == yes ]]; then activate_and_prune "${release_id}"; fi
}

# FLOOR's non-secret configuration is per release but outside it: the release is read-only and
# admission refuses any file it does not hold (root ADR-0134 §3). A same-directory hard link
# publishes it create-only, so concurrent installers cannot overwrite each other.
floor_config_path() {
  printf '%s/%s/building-register-floor.env' "${config_dir}" "$1"
}

install_floor_config_file() (
  set -Eeuo pipefail
  local release_id="$1" source="$2" expected="$3"
  local directory output staged=""
  require_release_id "${release_id}"
  [[ "${expected}" =~ ^[0-9a-f]{64}$ ]] || { echo 'invalid floor config sha256' >&2; exit 64; }
  [[ -f "${source}" && ! -L "${source}" ]] || { echo 'floor config must be a regular non-symlink file' >&2; exit 65; }
  directory="${config_dir}/${release_id}"
  output="$(floor_config_path "${release_id}")"
  for path in "${config_dir}" "${directory}"; do
    [[ ! -L "${path}" ]] || { echo 'floor config directory is a symlink' >&2; exit 65; }
    if [[ ! -e "${path}" ]]; then mkdir -m 0755 "${path}"; fi
    [[ -d "${path}" && "$(realpath -e "${path}")" == "$(realpath -ms "${path}")" ]] || {
      echo 'invalid floor config directory' >&2; exit 65;
    }
  done
  check_config() {
    [[ -f "${output}" && ! -L "${output}" &&
       "$(sha256sum "${output}" | awk '{print $1}')" == "${expected}" &&
       "$(stat -c '%a' "${output}")" == 644 ]] || {
      echo 'existing floor config differs or is not a regular 0644 file' >&2; return 65;
    }
    if [[ "$(id -u)" == 0 ]]; then
      [[ "$(stat -c '%u:%g' "${output}")" == 0:0 ]] || { echo 'floor config is not root-owned' >&2; return 65; }
    fi
  }
  if [[ -e "${output}" || -L "${output}" ]]; then check_config; exit; fi
  staged="$(mktemp "${directory}/.config.XXXXXX")"
  trap '[[ -z "${staged}" ]] || rm -f -- "${staged}"' EXIT
  cp -- "${source}" "${staged}"
  [[ "$(sha256sum "${staged}" | awk '{print $1}')" == "${expected}" ]] || {
    echo 'floor config changed while copying' >&2; exit 65;
  }
  chmod 644 "${staged}"
  if [[ "$(id -u)" == 0 ]]; then chown root:root "${staged}"; fi
  if ! ln -T -- "${staged}" "${output}"; then check_config; fi
)

validate_floor_config() {
  local source="$1" target="$2" mode="$3"
  [[ -f "${source}" && ! -L "${source}" ]] || { echo 'floor config must be a regular non-symlink file' >&2; return 65; }
  # The release example owns the key set. This only validates non-secret env transport;
  # image/network/endpoint semantics remain with the runtime validators.
  python3 - "${source}" "${target}" "${mode}" <<'PY'
import hashlib, grp, json, os, pathlib, pwd, re, secrets, stat, subprocess, sys
source, release = map(pathlib.Path, sys.argv[1:3])
mode = sys.argv[3]
example = release / 'infra/systemd/building-register-floor.env.example'
def fail():
    sys.exit('invalid public FLOOR configuration or release configuration schema')
def parse(text, example=False):
    values = {}
    for line in text.split('\n'):
        if not line.strip() or line.lstrip().startswith('#'):
            continue
        match = re.fullmatch(r'([A-Z][A-Z0-9_]*)=([A-Za-z0-9_./:@-]*)', line)
        if not match or match[1] in values or (not example and not match[2]):
            fail()
        values[match[1]] = match[2]
    return values
try:
    if not example.is_file() or example.is_symlink() or example.resolve() != example.absolute():
        fail()
    with source.open('rb') as handle:
        raw = handle.read(65537)
    if len(raw) > 65536 or any(byte < 32 and byte != 10 or byte == 127 for byte in raw):
        fail()
    values = parse(raw.decode('utf-8'))
    allowed = parse(example.read_text(encoding='utf-8'), example=True)
    if not allowed or values.keys() != allowed.keys():
        fail()
    if values.get('FOUNDATION_PLATFORM_REMOTE_LAKEHOUSE_ROOT') != str(release.resolve()):
        fail()
    # FLOOR's native image is the one this release's trusted build produced (root ADR-0134 §3):
    # the image ID build.json recorded, not any digest that merely looks pinned.
    build = release.resolve().parent.parent / 'artifacts' / release.name / 'build.json'
    if values.get('FOUNDATION_PLATFORM_LAKEHOUSE_CONTROL_IMAGE') != json.loads(build.read_text(encoding='utf-8')).get('publisher_image'):
        sys.exit('FOUNDATION_PLATFORM_LAKEHOUSE_CONTROL_IMAGE must be publisher_image from ' + str(build))
    witness = pathlib.Path(values['FOUNDATION_PLATFORM_BUILDING_REGISTER_FLOOR_HISTORY_PATH'])
    if (not witness.is_absolute() or '..' in witness.parts or
        witness.resolve(strict=True) != witness or release.resolve() in witness.parents):
        fail()
    # Production installs/state preparation run as root. Rootless temporary rehearsals own
    # their own fixture; they cannot write the protected production release/config paths.
    owners = {0, os.geteuid()}
    for parent in witness.parents:
        info = parent.lstat()
        sticky_root = info.st_uid == 0 and info.st_mode & stat.S_ISVTX
        if (not stat.S_ISDIR(info.st_mode) or info.st_uid not in owners or
            (info.st_mode & 0o022 and not sticky_root)):
            fail()
    descriptor = os.open(witness, os.O_RDONLY | os.O_NOFOLLOW | os.O_NONBLOCK)
    with os.fdopen(descriptor, 'rb') as handle:
        info = os.fstat(handle.fileno())
        if (not stat.S_ISREG(info.st_mode) or info.st_uid not in owners or
            info.st_nlink != 1 or info.st_mode & 0o222 or not 0 < info.st_size <= 65536):
            fail()
        handle.read(1)
    if os.geteuid() == 0:
        account = pwd.getpwnam('foundation-platform')
        service_gid = grp.getgrnam('foundation-platform').gr_gid
        # Root can read 0400 files that the host/native service and Spark cannot. Ask the
        # kernel under their actual IDs, without inheriting root's supplementary groups.
        probe = ('import os,stat,sys; '
                 'fd=os.open(sys.argv[1],os.O_RDONLY|os.O_NOFOLLOW|os.O_NONBLOCK); '
                 'assert stat.S_ISREG(os.fstat(fd).st_mode); os.read(fd,1); os.close(fd)')
        for reader_uid in {account.pw_uid, 185}:
            subprocess.run([sys.executable, '-I', '-c', probe, str(witness)],
                           user=reader_uid, group=service_gid, extra_groups=[],
                           stdin=subprocess.DEVNULL, stdout=subprocess.DEVNULL,
                           stderr=subprocess.DEVNULL, check=True, timeout=10)
except (OSError, UnicodeError, ValueError, KeyError, RuntimeError, subprocess.SubprocessError):
    fail()
if mode == 'hash':
    print(hashlib.sha256(raw).hexdigest())
    sys.exit(0)
if mode != 'state' or os.geteuid() != 0:
    fail()

# Only the two dedicated host namespaces are supported. The configuration owns the
# selected path; this allowlist is a privilege boundary, not another default.
state = pathlib.Path(values['FOUNDATION_PLATFORM_LAKEHOUSE_STATE_ROOT'])
ivy = pathlib.Path(values['FOUNDATION_PLATFORM_LAKEHOUSE_IVY_CACHE'])
approved_namespaces = ('/var/lib/foundation-platform/building-register-floor',
                       '/data/foundation-platform/building-register-floor')
if str(state) not in approved_namespaces:
    fail()
if str(state) != values['FOUNDATION_PLATFORM_LAKEHOUSE_STATE_ROOT']:
    fail()
if (str(ivy) != values['FOUNDATION_PLATFORM_LAKEHOUSE_IVY_CACHE'] or
    '..' in ivy.parts or ivy == state or state not in ivy.parents):
    fail()
uid, gid = account.pw_uid, service_gid
dropin = pathlib.Path('/etc/systemd/system/foundation-building-register-floor.service.d/10-state.conf')
dedicated = [state]
for part in ivy.relative_to(state).parts:
    dedicated.append(dedicated[-1] / part)

directory_flags = os.O_RDONLY | os.O_DIRECTORY | os.O_NOFOLLOW
descriptors = {pathlib.Path('/'): os.open('/', directory_flags)}

def open_directory(path, create=False):
    if path in descriptors:
        return descriptors[path]
    parent = open_directory(path.parent, create)
    if parent is None:
        return None
    created = None
    try:
        fd = os.open(path.name, directory_flags, dir_fd=parent)
    except FileNotFoundError:
        if not create:
            return None
        # A concurrent creator is an existing directory, never ours to chown.
        try:
            os.mkdir(path.name, 0o700, dir_fd=parent)
            created = os.stat(path.name, dir_fd=parent, follow_symlinks=False)
        except FileExistsError:
            pass
        fd = os.open(path.name, directory_flags, dir_fd=parent)
    info = os.fstat(fd)
    if created is not None:
        if ((created.st_dev, created.st_ino) != (info.st_dev, info.st_ino) or
            info.st_uid != 0 or info.st_mode & 0o777 != 0o700):
            os.close(fd)
            fail()
        if path in dedicated:
            os.fchown(fd, uid, gid)
        os.fchmod(fd, 0o2770 if path in dedicated else 0o755)
        info = os.fstat(fd)
    if (path in dedicated or str(path) in approved_namespaces) and (info.st_uid, info.st_gid) != (uid, gid):
        os.close(fd)
        fail()
    if path == dropin.parent and (info.st_uid != 0 or info.st_mode & 0o022):
        os.close(fd)
        fail()
    descriptors[path] = fd
    return fd

# Hold existing directory inodes through mutation; no later pathname chmod/chown.
for path in (*(pathlib.Path(name) for name in approved_namespaces), ivy, dropin.parent):
    open_directory(path)
if source.stat().st_uid != 0 or stat.S_IMODE(source.stat().st_mode) != 0o644:
    fail()
body = ('[Service]\nReadWritePaths=\nReadWritePaths=' +
        ' '.join('-' + path for path in approved_namespaces) + '\n').encode()
existing = None
parent = open_directory(dropin.parent)
if parent is not None:
    try:
        fd = os.open(dropin.name, os.O_RDONLY | os.O_NOFOLLOW | os.O_NONBLOCK, dir_fd=parent)
    except FileNotFoundError:
        pass
    else:
        with os.fdopen(fd, 'rb') as handle:
            info = os.fstat(handle.fileno())
            if not stat.S_ISREG(info.st_mode) or info.st_uid != 0:
                fail()
            existing = (handle.read(len(body) + 1), stat.S_IMODE(info.st_mode), info.st_gid)
for directory in dedicated:
    fd = open_directory(directory, create=True)
    if stat.S_IMODE(os.fstat(fd).st_mode) != 0o2770:
        os.fchmod(fd, 0o2770)
parent = open_directory(dropin.parent, create=True)
if existing == (body, 0o644, 0):
    sys.exit(0)
pending = '.state.' + secrets.token_hex(16)
fd = os.open(pending, os.O_WRONLY | os.O_CREAT | os.O_EXCL | os.O_NOFOLLOW, 0o600, dir_fd=parent)
try:
    with os.fdopen(fd, 'wb') as handle:
        handle.write(body)
        os.fchmod(handle.fileno(), 0o644)
        os.fchown(handle.fileno(), 0, 0)
    os.replace(pending, dropin.name, src_dir_fd=parent, dst_dir_fd=parent)
finally:
    try:
        os.unlink(pending, dir_fd=parent)
    except FileNotFoundError:
        pass
PY
}

install_floor_config() {
  local release_id="$1" source="$2" expected target
  require_release_id "${release_id}"
  assert_installed_release "${release_id}"
  target="$(release_path "${release_id}")"
  expected="$(validate_floor_config "${source}" "${target}" hash)" || exit 65
  install_floor_config_file "${release_id}" "${source}" "${expected}"
}

prepare_floor_state() {
  local target release_id
  target="$(realpath -e "${release_root}/current")"
  release_id="${target##*/}"
  require_release_id "${release_id}"
  assert_installed_release "${release_id}"
  [[ "${target}" == "$(realpath -ms "$(release_path "${release_id}")")" ]] || {
    echo 'current FLOOR release is outside the installed release tree' >&2; return 65;
  }
  validate_floor_config "$(floor_config_path "${release_id}")" "${target}" state
}

rollback_release() {
  local previous_target previous_id current_target
  prepare_mutable_state
  [[ -L "${release_root}/previous" ]] || {
    printf 'no previous release is available\n' >&2
    exit 66
  }
  previous_target="$(readlink "${release_root}/previous")"
  [[ "${previous_target}" =~ ^releases/([0-9a-f]{40})$ ]] || {
    printf 'previous release link is invalid: %s\n' "${previous_target}" >&2
    exit 65
  }
  previous_id="${BASH_REMATCH[1]}"
  assert_installed_release "${previous_id}"
  current_target="$(readlink "${release_root}/current")"
  atomic_link "${previous_target}" "${release_root}/current"
  atomic_link "${current_target}" "${release_root}/previous"
}

# Every deploy left about 0.9GB on the root disk — releases/<sha>, artifacts/<sha>, config/<sha>
# and two image tags — and nothing ever took it back: 49 releases were kept, and on 2026-10-02 the
# root disk filled to zero twice. This keeps what rollback and the emergency return need, the
# newest few, and removes the rest. The control checkout's releases are pruned the same way.
#
# Fail closed: an unreadable contract, a `current` that is not a release link, or a Docker that
# cannot list its containers removes nothing. A release a running process or container still
# references is refused by name, not removed. Exit 75 when anything was refused.
#
# It holds admission's release build lock for its whole run, taken with admission's own code: a
# build writes artifacts/<sha> and image tags while it runs. A held lock skips the prune (exit 0,
# nothing removed) rather than raising the failure alarm; the next activation, or `prune` by hand,
# catches up.
prune_releases() {
  python3 - "${retention_contract}" "${release_root}" "${control_releases_dir}" "${admission}" <<'PY'
import contextlib, importlib.machinery, importlib.util, json, os, re, shutil, stat, subprocess, sys
from pathlib import Path

SHA = re.compile(r"[0-9a-f]{40}")
contract_path, release_root, control_releases, admission_path = map(Path, sys.argv[1:5])
IMAGES = ("foundation-outbox-publisher", "foundation-tippecanoe")


def refuse(message):
    print(f"prune refused: {message}; nothing was removed", file=sys.stderr)
    sys.exit(65)


build_lock = contextlib.ExitStack()
try:
    loader = importlib.machinery.SourceFileLoader("foundation_release_admission", str(admission_path))
    admission = importlib.util.module_from_spec(importlib.util.spec_from_loader(loader.name, loader))
    loader.exec_module(admission)
    build_lock.enter_context(admission.release_build_lock())
except ValueError as error:
    print(f"prune-skipped: {error}; nothing was removed. Run prune after the build finishes.")
    sys.exit(0)
except (OSError, ImportError, SyntaxError, AttributeError) as error:
    refuse(f"cannot take the release build lock through {admission_path}: {error!r}")


try:
    contract = json.loads(contract_path.read_text(encoding="utf-8"))
    emergency, keep_newest = contract["emergency_release"], contract["keep_newest"]
except (OSError, ValueError, KeyError, TypeError) as error:
    refuse(f"retention contract {contract_path} is unreadable: {error!r}")
if not isinstance(emergency, str) or not SHA.fullmatch(emergency):
    refuse(f"{contract_path}: emergency_release must be a 40-character Git SHA")
if type(keep_newest) is not int or not 1 <= keep_newest <= 20:
    refuse(f"{contract_path}: keep_newest must be an integer from 1 to 20")


def link_release(link, required):
    if not link.is_symlink():
        if required or link.exists():
            refuse(f"{link} is not a release link")
        return None
    match = re.fullmatch(r"releases/([0-9a-f]{40})", os.readlink(link))
    if not match:
        refuse(f"{link} does not point at releases/<sha>: {os.readlink(link)}")
    return match[1]


def ids_in(directory):
    if not directory.is_dir():
        return set()
    return {entry.name for entry in directory.iterdir() if SHA.fullmatch(entry.name)}


def disk_bytes(path):
    total, seen = 0, set()
    for root, _, files in os.walk(path):
        for name in [root, *(os.path.join(root, file) for file in files)]:
            info = os.lstat(name)
            if (info.st_dev, info.st_ino) not in seen:
                seen.add((info.st_dev, info.st_ino))
                total += info.st_blocks * 512
    return total


def remove_tree(path):
    """Admitted releases and artifacts are read-only; lift that only on what is being removed."""
    if not path.exists() and not path.is_symlink():
        return 0
    if path.is_symlink() or not path.is_dir():
        raise OSError(f"{path} is not a plain directory")
    size = disk_bytes(path)
    for root, _, _ in os.walk(path):
        os.chmod(root, stat.S_IRWXU)
    shutil.rmtree(path)
    return size


def docker(*args):
    try:
        return subprocess.run(["docker", *args], capture_output=True, text=True, timeout=300)
    except (OSError, subprocess.SubprocessError) as error:
        return subprocess.CompletedProcess(args, 127, "", str(error))


class Unanswered(Exception):
    """Docker answered, but not with what was asked: nothing may be decided from it."""


def image(reference):
    """(id, size) of a local image, or None when Docker does not have it."""
    found = docker("image", "inspect", "--format", "{{.Id}} {{.Size}}", reference)
    if found.returncode != 0:
        return None
    fields = found.stdout.split()
    if len(fields) != 2 or not fields[1].isdigit():
        raise Unanswered(f"docker image inspect {reference} answered {found.stdout.strip()[:200]!r}")
    return fields[0], int(fields[1])


def image_or_none(reference):
    try:
        return image(reference)
    except Unanswered:
        return None


def newest(ids, *roots):
    def installed(release_id):
        for root in roots:
            path = root / release_id
            if path.exists():
                return path.lstat().st_mtime
        return 0
    return sorted(ids, key=lambda release_id: (installed(release_id), release_id), reverse=True)[:keep_newest]


# What every running process holds: working directory, executable, root, open files, arguments and
# environment. A unit started from an older `current` still runs out of that release's directory.
def process_references():
    held = []
    for pid in os.listdir("/proc"):
        if not pid.isdigit() or int(pid) == os.getpid():
            continue
        base, strings = Path("/proc", pid), []
        for name in ("cwd", "exe", "root"):
            try:
                strings.append(os.readlink(base / name))
            except OSError:
                pass
        try:
            for fd in os.listdir(base / "fd"):
                try:
                    strings.append(os.readlink(base / "fd" / fd))
                except OSError:
                    pass
        except OSError:
            pass
        for name in ("cmdline", "environ"):
            try:
                strings.extend((base / name).read_bytes().decode("utf-8", "replace").split("\0"))
            except OSError:
                pass
        try:
            command = (base / "comm").read_text(encoding="utf-8").strip()
        except OSError:
            command = "?"
        held.append((f"process {pid} ({command})", [value for value in strings if value]))
    return held


def container_references():
    running = docker("ps", "-q", "--no-trunc")
    if running.returncode != 0:
        refuse(f"docker cannot list running containers: {running.stderr.strip()}")
    ids = running.stdout.split()
    if not ids:
        return []
    found = docker("inspect", "--format",
                   "{{.Name}} {{.Image}} {{.Config.Image}}{{range .Mounts}} {{.Source}}{{end}}", *ids)
    if found.returncode != 0:
        refuse(f"docker cannot inspect running containers: {found.stderr.strip()}")
    held = []
    for line in found.stdout.splitlines():
        fields = line.split()
        if fields:
            held.append((f"container {fields[0].lstrip('/')}", fields[1:]))
    return held


def holder(paths, images, held):
    for who, strings in held:
        for value in strings:
            if value in images or any(path in value for path in paths):
                return who
    return None


def recorded_images(release_id):
    """Image IDs this release's build.json names."""
    try:
        build = json.loads((release_root / "artifacts" / release_id / "build.json").read_text(encoding="utf-8"))
        return {value for key, value in build.items() if key.endswith("_image") and isinstance(value, str)}
    except (OSError, ValueError, AttributeError):
        return set()


releases = release_root / "releases"
current = link_release(release_root / "current", required=True)
previous = link_release(release_root / "previous", required=False)
present = ids_in(releases) | ids_in(release_root / "artifacts") | ids_in(release_root / "config")
keep = {}
keep[current] = "current"
if previous:
    keep.setdefault(previous, "previous")
keep.setdefault(emergency, "emergency")  # retention rule: the emergency return's release
for release_id in newest(present, releases, release_root / "artifacts", release_root / "config"):
    keep.setdefault(release_id, "newest")

control_current = None
if control_releases.is_dir():
    control_current = link_release(control_releases.parent / "current", required=True)
control_present = ids_in(control_releases)
control_keep = {}
if control_current:
    control_keep[control_current] = "current"
for release_id in newest(control_present, control_releases):
    control_keep.setdefault(release_id, "newest")

# A cached build gives two releases the same image ID (tippecanoe rarely changes). An image a kept
# release's build.json names belongs to that release: it neither ties an old release to a running
# container nor goes when the old release's last tag on it does.
kept_images = set().union(*(recorded_images(release_id) for release_id in keep))
kept_tagged = {found[0] for release_id in keep for name in IMAGES
               if (found := image_or_none(f"{name}:{release_id}"))}

held = process_references() + container_references()
removed = refused = failed = 0
freed = 0
for release_id in sorted(present):
    if release_id in keep:
        print(f"prune kept {release_id} ({keep[release_id]})")
        continue
    paths = [str(root / release_id) for root in (releases, release_root / "artifacts", release_root / "config")]
    try:
        tags = {f"{name}:{release_id}": image(f"{name}:{release_id}") for name in IMAGES}
    except Unanswered as error:
        print(f"prune refused {release_id}: {error}", file=sys.stderr)
        refused += 1
        continue
    own = recorded_images(release_id) | {found[0] for found in tags.values() if found}
    who = holder(paths, (own - kept_images) | set(tags), held)
    if who:
        print(f"prune refused {release_id}: still referenced by {who}", file=sys.stderr)
        refused += 1
        continue
    try:
        sizes = {"release": remove_tree(releases / release_id),
                 "artifacts": remove_tree(release_root / "artifacts" / release_id),
                 "config": remove_tree(release_root / "config" / release_id),
                 "images": 0}
    except OSError as error:
        print(f"prune failed {release_id}: {error}", file=sys.stderr)
        failed += 1
        continue
    # The tag goes; the image goes with it unless another tag or any container still uses it,
    # which Docker decides and reports. The last tag on an image a kept release built stays:
    # removing it would delete that release's image.
    for tag, found in tags.items():
        if not found:
            continue
        if found[0] in kept_images and found[0] not in kept_tagged:
            print(f"prune kept image {tag}: {found[0]} is a kept release's build and no kept tag holds it")
            continue
        gone = docker("image", "rm", tag)
        if gone.returncode != 0:
            print(f"prune kept image {tag}: {gone.stderr.strip()}", file=sys.stderr)
        elif image_or_none(found[0]) is None:
            sizes["images"] += found[1]
    freed += sum(sizes.values())
    removed += 1
    print(f"prune removed {release_id} " + " ".join(f"{key}={value}" for key, value in sizes.items()))

for release_id in sorted(control_present):
    if release_id in control_keep:
        print(f"prune kept control {release_id} ({control_keep[release_id]})")
        continue
    path = control_releases / release_id
    who = holder([str(path)], set(), held)
    if who:
        print(f"prune refused control {release_id}: still referenced by {who}", file=sys.stderr)
        refused += 1
        continue
    try:
        size = remove_tree(path)
    except OSError as error:
        print(f"prune failed control {release_id}: {error}", file=sys.stderr)
        failed += 1
        continue
    freed += size
    removed += 1
    print(f"prune removed control {release_id} release={size}")

verdict = "prune-ok" if not refused and not failed else "prune-incomplete"
print(f"{verdict} removed={removed} refused={refused} failed={failed} freed_bytes={freed} "
      f"freed_gib={freed / 2**30:.2f}")
sys.exit(0 if verdict == "prune-ok" else 75)
PY
}

# Retention runs after the switch, never instead of it: a failed prune leaves the new release
# active and the deploy succeeded, but it must not pass quietly, since the next deploys fill the
# disk again (runbook: 릴리스 보존).
prune_after_activation() {
  local status=0
  prune_releases || status=$?
  [[ "${status}" == 0 ]] && return 0
  printf '\n!!! RELEASE PRUNE FAILED (exit %s) after activating %s; the activation stands.\n' \
    "${status}" "$1" >&2
  printf '!!! Old releases are still on the root disk. Fix the cause above, then run: foundation-release.sh prune\n\n' >&2
  if command -v logger >/dev/null 2>&1; then
    logger -p user.err -t foundation-release "release prune failed (exit ${status}) after activating $1" || true
  fi
  return 0
}

# Every path that switches `current` to a new release prunes after it, the same way: `install`
# once activated without pruning, so a host deployed by `install` alone kept every release.
activate_and_prune() {
  activate_release "$1"
  prune_after_activation "$1"
}

verify_runtime_schema() {
  assert_current_release
  # Deploying source cannot move the schema: the migrations are compiled into the runtime image
  # by `sqlx::migrate!`. On 2026-09-01 that gap was six weeks and thirty-three-minus-four
  # migrations wide, with every catalog table empty and the API answering `[]`, and no step
  # anywhere compared the two. This is that step.
  local checker="${release_root}/current/scripts/deploy/assert-runtime-migrations.sh"
  [[ -x "${checker}" ]] || {
    printf 'runtime migration check is missing from the release: %s\n' "${checker}" >&2
    exit 66
  }
  local environment="${release_root}/current/scripts/deploy/assert-runtime-environment.sh"
  [[ -x "${environment}" ]] || {
    printf 'runtime environment check is missing from the release: %s\n' "${environment}" >&2
    exit 66
  }
  # The environment first. A variable the compose files require and the host does not carry
  # surfaces as an interpolation error in the middle of a migration run — after the image
  # rebuild, with nothing having said beforehand that the file was behind. Measured 2026-09-01
  # while repairing the schema gap: six variables were missing, and compose named one per
  # attempt, so the hole looked two deep until the whole file was compared (root ADR-0071).
  "${environment}" "${release_root}/current"
  verify_runtime_secrets
  "${checker}" "${release_root}/current"
}

# Every environment file the release's units load exists, is owned and no more open than the
# runtime-secrets contract says, and holds every name it declares (root ADR-0153). Names only: the
# checker prints a missing name, never a value. On 2026-10-05 a unit's script required the lakehouse
# reader key that none of its files held, and the first run found out after writing to Bronze.
verify_runtime_secrets() {
  local secrets="${release_root}/current/scripts/deploy/runtime_secrets.py"
  [[ -f "${secrets}" ]] || {
    printf 'runtime secrets check is missing from the release: %s\n' "${secrets}" >&2
    exit 66
  }
  # FOUNDATION_PLATFORM_SECRETS_ROOT is the filesystem root the group paths are under: `/` on the
  # host, a fake host in foundation-release-test.sh.
  python3 -I "${secrets}" --area "${release_root}/current" host --root "${FOUNDATION_PLATFORM_SECRETS_ROOT:-/}" || {
    printf 'the host environment files do not match config/runtime-secrets.contract.json; see above (names only)\n' >&2
    exit 65
  }
}

migrate_runtime() {
  assert_current_release
  # Rebuild before applying. The migrator is the release's own binary and the migrations live
  # inside it, so an image built from an older tree applies an older set however new the source
  # on disk is — which is exactly how the runtime came to be six weeks behind.
  local runtime="${release_root}/current/scripts/deploy/foundation-runtime.sh"
  [[ -x "${runtime}" ]] || {
    printf 'runtime compose wrapper is missing from the release: %s\n' "${runtime}" >&2
    exit 66
  }
  "${runtime}" build foundation-api
  # Asks for the end state, and names no step on the way to it.
  #
  # The compose file already declares the order — postgres, bootstrap, migrate, grants,
  # finalize, api — each link a `service_completed_successfully`. This used to run
  # `up --no-deps postgres` and then `run foundation-migrate`, which is that chain written a
  # second time and stopped in the middle. On 2026-09-02 the consequence surfaced: the database
  # had every migration and the API answered `permission denied for schema catalog`, because
  # `foundation-runtime-grants` never ran. Nothing said so — `/health` does not touch the
  # database, so the stack looked up for a day.
  #
  # `foundation-api` is the last link, so requiring it requires all of them, in the order the
  # compose file owns. `--wait` makes the command finish when the state is reached rather than
  # when the request was accepted.
  "${runtime}" up -d --wait foundation-api
  # The identity loopback sidecars are asked for separately, and not redundantly: they depend
  # on foundation-api, and compose only pulls dependencies in the direction of the arrow —
  # asking for the api alone leaves its own loopback listeners down, which surfaced on the
  # first identity bring-up as policy calls dying inside a healthy-looking container.
  "${runtime}" up -d --wait identity-zitadel-loopback identity-api-loopback
  verify_runtime_schema
  migrate_lakehouse
}

# The lakehouse half of `migrate` (root ADR-0124): every published lakehouse table is brought to
# the release's contracts -- columns added in contract order, order fixed by metadata, registered
# backfills run -- and anything that cannot be (a column the contract does not declare, a required
# column with no backfill) stops the deploy here, the way a failed database migration does.
# Temporary compatibility exceptions are owned and reported by the migration job (ADR-0124).
install_lakehouse_migration_unit() {
  install -o root -g root -m 0644 -t /etc/systemd/system \
    "${release_root}/current/infra/systemd/foundation-lakehouse-migrate.service"
  install_release_admission foundation-lakehouse-migrate.service
  install -d -o foundation-platform -g foundation-platform /var/lib/foundation-platform/lakehouse-migrate
}

migrate_lakehouse() {
  assert_current_release
  install_lakehouse_migration_unit
  systemctl daemon-reload
  # A oneshot's start returns when it has finished, with its result.
  if systemctl start foundation-lakehouse-migrate.service; then
    journalctl -u foundation-lakehouse-migrate.service --since "-2h" --no-pager -o cat |
      grep -a '^lakehouse-migrate apply:' | tail -1
  else
    journalctl -u foundation-lakehouse-migrate.service --since "-2h" --no-pager -o cat |
      grep -a '^lakehouse-migrate' | tail -40 >&2
    printf 'lakehouse migration failed; the release is installed but not migrated\n' >&2
    exit 75
  fi
}

status() {
  printf 'release_root=%s\n' "${release_root}"
  printf 'state_root=%s\n' "${state_root}"
  printf 'current=%s\n' "$(readlink "${release_root}/current" 2>/dev/null || true)"
  printf 'previous=%s\n' "$(readlink "${release_root}/previous" 2>/dev/null || true)"
}

command="${1:-}"
case "${command}" in
  prepare)
    [[ "$#" == 3 ]] || usage
    install_release "$2" "$3" no
    ;;
  floor-config)
    [[ "$#" == 3 ]] || usage
    install_floor_config "$2" "$3"
    ;;
  install)
    [[ "$#" == 3 ]] || usage
    install_release "$2" "$3"
    # A deploy that leaves the running schema behind has not finished, and saying otherwise is
    # what let the runtime sit six weeks and twenty-nine migrations behind while three deploys
    # reported success. The release is installed and activated by this point, so the operator
    # can run `migrate` — this refuses to call the deploy done, it does not undo it.
    verify_runtime_schema
    ;;
  activate)
    [[ "$#" == 2 ]] || usage
    require_release_id "$2"
    mkdir -p "${releases_dir}" "${state_root}/recovery"
    prepare_mutable_state
    activate_and_prune "$2"
    ;;
  migrate)
    [[ "$#" == 1 ]] || usage
    migrate_runtime
    ;;
  verify)
    [[ "$#" == 1 ]] || usage
    verify_runtime_schema
    ;;
  timers)
    # The release installs and enables its own systemd timers (root ADR-0077). The unit files
    # ship inside the release, so "which timers exist" has exactly one home; installing them by
    # hand is how the backup timer's install steps and the deployed tree drifted apart before.
    # Idempotent: reinstalling the same files and re-enabling an enabled timer are no-ops.
    [[ "$#" == 1 || "$#" == 2 ]] || usage
    assert_current_release
    # No unit is installed whose environment files the host does not have (root ADR-0153).
    verify_runtime_secrets
    # FLOOR's unit is installed only with a valid FLOOR config and state, and nothing else waits on
    # them: an invalid FLOOR config used to stop this step before it installed any unit, retired
    # any timer, regenerated the scheduler's sudoers or enabled the backup timer.
    floor_unit=foundation-building-register-floor.service
    floor_status=0
    prepare_floor_state || floor_status=$?
    # Every unit the release ships, not a list of them here: a job's service added to infra/systemd
    # is installed by the same release that lists it in orchestration/jobs.v1.json.
    for unit in "${release_root}"/current/infra/systemd/*.service \
      "${release_root}"/current/infra/systemd/*.timer; do
      [[ "${unit##*/}" != "${floor_unit}" || "${floor_status}" == 0 ]] || continue
      install -o root -g root -m 0644 -t /etc/systemd/system "${unit}"
    done
    # The fold was one complex-only unit before it became a per-unit template; a host upgraded
    # from then still carries it, and it would fold complex a second time every hour.
    if [[ -e /etc/systemd/system/foundation-map-edit-fold.timer ]]; then
      systemctl disable --now foundation-map-edit-fold.timer || true
      rm -f /etc/systemd/system/foundation-map-edit-fold.timer \
        /etc/systemd/system/foundation-map-edit-fold.service
    fi
    # A job Airflow runs (orchestration/jobs.v1.json `enabled`) loses its timer in the release that
    # switches its DAG on (root ADR-0122 §4), so it runs in exactly one place. Its service stays:
    # systemd still runs it, Airflow only starts it.
    jobs_file="${release_root}/current/orchestration/jobs.v1.json"
    # systemd owns every scheduled entry point, including a direct `systemctl start`; a check in
    # the SSH dispatcher alone would leave that path open. The migration unit is not scheduled,
    # so it is named here too.
    install_lakehouse_migration_unit
    while read -r service; do
      [[ -n "${service}" ]] || continue
      install_release_admission "${service}"
    done < <(python3 -c '
import json, sys
for job in json.load(open(sys.argv[1]))["jobs"]:
    print(job["systemd_service"])
' "${jobs_file}")
    while read -r timer; do
      [[ -n "${timer}" ]] || continue
      if [[ -e "/etc/systemd/system/${timer}" ]]; then
        systemctl disable --now "${timer}" || true
        rm -f "/etc/systemd/system/${timer}"
        printf 'timer retired to airflow: %s\n' "${timer}"
      fi
    done < <(python3 -c '
import json, sys
for job in json.load(open(sys.argv[1]))["jobs"]:
    if job["enabled"]:
        print(job["systemd_timer"])
' "${jobs_file}")
    install_scheduler_access "${jobs_file}" "${2:-}"
    # Working directories the fold and the stewardship cycle write, whoever starts them. Their
    # lakehouse workspaces are written by the Spark container too (uid 185), so they are 0777:
    # the stewardship one was made 0755 by the script itself, Spark's write check refused it, and
    # the cycle failed at its first step on every run (found 2026-10-01). The fold's had been
    # made 0777 by hand from its runbook.
    install -d -o foundation-platform -g foundation-platform \
      /var/lib/foundation-platform/map-edit-fold /var/lib/foundation-platform/lineage-stewardship
    # The legal-dong code collection writes its handoffs here, and the stewardship cycle, which loads
    # them, names it in ReadWritePaths: systemd refuses to start a unit whose path is missing
    # (root ADR-0143).
    install -d -o foundation-platform -g foundation-platform /var/lib/foundation-platform/legal-dong-code
    # The cadastral edition check keeps its runs and proposed contract entries here (root ADR-0148).
    install -d -o foundation-platform -g foundation-platform /var/lib/foundation-platform/vworld-parcel-edition
    # Like legal-dong-code above, for the 필지고유번호변동연혁 collection's handoffs (root ADR-0150): the stewardship
    # cycle loads them and names the path, so it must exist before that unit next starts.
    install -d -o foundation-platform -g foundation-platform /var/lib/foundation-platform/parcel-number-change
    install -d -o foundation-platform -g foundation-platform -m 0777 \
      /var/lib/foundation-platform/map-edit-fold/lakehouse \
      /var/lib/foundation-platform/lineage-stewardship/lakehouse
    # The by-PNU bakes' work files: on the data disk, the only path their unit may write.
    install -d -o foundation-platform -g foundation-platform /data/foundation-platform/by-pnu-bake
    systemctl daemon-reload
    # The database backup is host infrastructure, not a data job: it stays a systemd timer
    # (root ADR-0118 §1). Every data job is started by Airflow (root ADR-0122).
    systemctl enable --now foundation-postgres-backup.timer
    # The host deploys main by itself once it names its deployer (root ADR-0159); a host without
    # that file is deployed by hand, and its timer stays off. Deploying is not a data job either.
    autodeploy=off
    if [[ -r /etc/foundation-platform/release-deploy.conf ]]; then
      systemctl enable --now foundation-autodeploy.timer
      autodeploy="$(systemctl is-enabled foundation-autodeploy.timer)"
    fi
    if [[ "${floor_status}" != 0 ]]; then
      printf 'timers incomplete: %s was not installed; its FLOOR config or state is invalid\n' \
        "${floor_unit}" >&2
      exit 65
    fi
    printf 'timers-ok backup=%s autodeploy=%s\n' \
      "$(systemctl is-enabled foundation-postgres-backup.timer)" "${autodeploy}"
    ;;
  rollback)
    [[ "$#" == 1 ]] || usage
    rollback_release
    ;;
  prune)
    [[ "$#" == 1 ]] || usage
    prune_releases
    ;;
  deployer-access)
    [[ "$#" == 2 || "$#" == 3 ]] || usage
    install_deployer_access "$2" "${3:-}"
    ;;
  status)
    [[ "$#" == 1 ]] || usage
    status
    ;;
  *) usage ;;
esac
