#!/usr/bin/env bash
set -Eeuo pipefail

release_root="${FOUNDATION_PLATFORM_RELEASE_ROOT:-/opt/foundation-platform}"
state_root="${FOUNDATION_PLATFORM_STATE_ROOT:-/var/lib/foundation-platform}"
releases_dir="${release_root}/releases"
lakehouse_uid="${FOUNDATION_PLATFORM_LAKEHOUSE_UID:-185}"
lakehouse_gid="${FOUNDATION_PLATFORM_LAKEHOUSE_GID:-185}"

usage() {
  cat >&2 <<'USAGE'
usage:
  foundation-release.sh install <40-char-git-sha> <source.tar.gz>
  foundation-release.sh activate <40-char-git-sha>
  foundation-release.sh migrate
  foundation-release.sh verify
  foundation-release.sh timers [<airflow-scheduler-ssh-public-key-file>]
  foundation-release.sh rollback
  foundation-release.sh status
USAGE
  exit 64
}

require_release_id() {
  local release_id="$1"
  [[ "${release_id}" =~ ^[0-9a-f]{40}$ ]] || {
    printf 'release id must be a lowercase 40-character Git SHA: %s\n' "${release_id}" >&2
    exit 64
  }
}

release_path() {
  printf '%s/%s' "${releases_dir}" "$1"
}

# Airflow's only way onto this host (root ADR-0122 §2): an account that cannot log in, whose one
# SSH key runs one command, which may start and stop exactly the services of enabled jobs. All of
# it is rebuilt from the release on every `timers`, so a job switched on or off changes it too.
scheduler_account=foundation-scheduler
scheduler_home=/var/lib/foundation-scheduler

install_scheduler_access() {
  local jobs_file="$1" public_key_file="$2" key subnet sudoers staged
  if ! id "${scheduler_account}" >/dev/null 2>&1; then
    useradd --system --home-dir "${scheduler_home}" --create-home --shell /bin/bash \
      --groups systemd-journal "${scheduler_account}"
    # No password and not locked: sshd still accepts its key, nothing accepts a password.
    usermod -p '*' "${scheduler_account}"
  fi
  install -d -o "${scheduler_account}" -g "${scheduler_account}" -m 0700 "${scheduler_home}/.ssh"
  if [[ -n "${public_key_file}" ]]; then
    key="$(cat "${public_key_file}")"
    [[ "${key}" =~ ^ssh-ed25519\ [A-Za-z0-9+/=]+(\ [A-Za-z0-9@._-]+)?$ ]] || {
      printf 'scheduler key must be one ssh-ed25519 public key line: %s\n' "${public_key_file}" >&2
      exit 65
    }
    # The key works only from the scheduler's own network, read from Docker rather than written
    # down: start Airflow (airflow-runtime.sh up -d) before installing it.
    subnet="$(docker network inspect airflow_default \
      -f '{{range .IPAM.Config}}{{.Subnet}} {{end}}' 2>/dev/null | awk '{print $1}')"
    [[ "${subnet}" =~ ^[0-9]{1,3}(\.[0-9]{1,3}){3}/[0-9]{1,2}$ ]] || {
      printf 'the airflow_default network is missing; run airflow-runtime.sh up -d first\n' >&2
      exit 69
    }
    # No pty, forwarding or agent; the command is fixed whatever the client asks for.
    printf 'restrict,from="%s",command="%s/current/scripts/ops/start-scheduled-job.sh" %s\n' \
      "${subnet}" "${release_root}" "${key}" >"${scheduler_home}/.ssh/authorized_keys"
    chown "${scheduler_account}:${scheduler_account}" "${scheduler_home}/.ssh/authorized_keys"
    chmod 0600 "${scheduler_home}/.ssh/authorized_keys"
  fi
  # Exact command lines, one start and one stop per enabled job's service; nothing else.
  staged="$(mktemp)"
  python3 - "${jobs_file}" "${scheduler_account}" >"${staged}" <<'PY'
import json, re, sys
jobs, account = sys.argv[1], sys.argv[2]
print("# Generated by foundation-release.sh timers from orchestration/jobs.v1.json (root ADR-0122).")
for job in json.load(open(jobs))["jobs"]:
    service = job["systemd_service"]
    if not re.fullmatch(r"foundation-[a-z0-9-]+(@[a-z0-9-]+)?\.service", service):
        sys.exit(f"refusing service name {service!r}")
    if job["enabled"]:
        print(f"{account} ALL=(root) NOPASSWD: /usr/bin/systemctl start --no-block {service}, "
              f"/usr/bin/systemctl stop {service}")
PY
  sudoers=/etc/sudoers.d/foundation-scheduler
  visudo -cqf "${staged}" || {
    rm -f "${staged}"
    printf 'generated sudoers did not validate; %s left unchanged\n' "${sudoers}" >&2
    exit 65
  }
  install -o root -g root -m 0440 "${staged}" "${sudoers}"
  rm -f "${staged}"
  printf 'scheduler-access-ok account=%s key=%s\n' "${scheduler_account}" \
    "$([[ -s "${scheduler_home}/.ssh/authorized_keys" ]] && echo installed || echo missing)"
}

prepare_mutable_state() {
  local directory
  [[ "${lakehouse_uid}" =~ ^[0-9]+$ && "${lakehouse_gid}" =~ ^[0-9]+$ ]] || {
    printf 'lakehouse uid and gid must be numeric\n' >&2
    exit 64
  }
  for directory in "${state_root}/lakehouse" "${state_root}/remote-lakehouse"; do
    mkdir -p "${directory}"
    if [[ "$(id -u)" -eq 0 ]]; then
      chown "${lakehouse_uid}:${lakehouse_gid}" "${directory}"
    fi
    chmod 0770 "${directory}"
    [[ -w "${directory}" || "$(id -u)" -eq 0 ]] || {
      printf 'mutable state directory is not writable: %s\n' "${directory}" >&2
      exit 73
    }
  done
}

atomic_link() {
  local target="$1"
  local link_path="$2"
  local pending="${link_path}.next.$$"
  ln -s "${target}" "${pending}"
  mv -Tf "${pending}" "${link_path}"
}

assert_installed_release() {
  local release_id="$1"
  local path
  path="$(release_path "${release_id}")"
  [[ -d "${path}" ]] || {
    printf 'release is not installed: %s\n' "${release_id}" >&2
    exit 66
  }
  [[ "$(cat "${path}/.foundation-release-id")" == "${release_id}" ]] || {
    printf 'release identity evidence is missing or invalid: %s\n' "${path}" >&2
    exit 65
  }
}

activate_release() {
  local release_id="$1"
  local next_target="releases/${release_id}"
  local current_target=""
  assert_installed_release "${release_id}"

  if [[ -L "${release_root}/current" ]]; then
    current_target="$(readlink "${release_root}/current")"
  elif [[ -e "${release_root}/current" ]]; then
    printf 'current exists but is not a symbolic link\n' >&2
    exit 65
  fi

  if [[ -n "${current_target}" && "${current_target}" != "${next_target}" ]]; then
    atomic_link "${current_target}" "${release_root}/previous"
  fi
  atomic_link "${next_target}" "${release_root}/current"
}

# A release is a tree rooted at platforms/foundation-platform, and this is where that is
# enforced — before anything is staged or activated. On 2026-09-03 an archive of the monorepo
# root installed, activated, and only then failed the schema check because scripts/deploy/ was
# a level deeper than every path this script derives. By that point the release id was sealed
# to the wrong archive's sha256 and could never be installed correctly again. The marker asked
# for is this script's own runtime schema check: the thing `install` will need to run last.
validate_archive_is_a_release() {
  local archive="$1" listing
  # The listing is captured, not piped into the match. Piped, `grep -q` exits on its first hit
  # and closes the pipe; tar dies of SIGPIPE (141), and under `pipefail` the pipeline fails even
  # though the file was found — so this gate refused every valid archive large enough for tar to
  # still be writing when grep matched. That is exactly what happened on 2026-09-03: the first
  # real deployment after this gate merged was refused with the "not a release tree" message,
  # while the same grep run by hand on the same archive counted one match. The single-file
  # rehearsal fixture never triggered it, because tar had already finished. A verdict must never
  # sit downstream of a pipe whose producer can be killed by the verdict being reached.
  listing="$(tar -tzf "${archive}")"
  grep -qE '^(\./)?scripts/deploy/assert-runtime-migrations\.sh$' <<<"${listing}" || {
    printf 'archive is not a release tree: scripts/deploy/assert-runtime-migrations.sh is not at its root\n' >&2
    printf 'archive the subtree, not the monorepo: git archive "<sha>:platforms/foundation-platform"\n' >&2
    exit 65
  }
}

validate_archive_paths() {
  local archive="$1"
  local entry normalized
  while IFS= read -r entry; do
    normalized="${entry#./}"
    [[ -z "${normalized}" || "${normalized}" == "." ]] && continue
    if [[ "${normalized}" == /* || "${normalized}" =~ (^|/)\.\.(/|$) ]]; then
      printf 'archive contains unsafe path: %s\n' "${entry}" >&2
      exit 65
    fi
  done < <(tar -tzf "${archive}")
}

install_release() {
  local release_id="$1"
  local archive="$2"
  local target archive_sha recorded_sha staging=""
  require_release_id "${release_id}"
  [[ -f "${archive}" ]] || {
    printf 'release archive does not exist: %s\n' "${archive}" >&2
    exit 66
  }
  validate_archive_paths "${archive}"
  validate_archive_is_a_release "${archive}"
  archive_sha="$(sha256sum "${archive}" | awk '{print $1}')"
  target="$(release_path "${release_id}")"

  mkdir -p "${releases_dir}" "${state_root}/recovery"
  prepare_mutable_state
  if [[ -e "${target}" ]]; then
    assert_installed_release "${release_id}"
    recorded_sha="$(cat "${target}/.foundation-release-archive-sha256")"
    [[ "${recorded_sha}" == "${archive_sha}" ]] || {
      printf 'release id already exists with a different archive: %s\n' "${release_id}" >&2
      exit 65
    }
    activate_release "${release_id}"
    return
  fi

  staging="$(mktemp -d "${releases_dir}/.${release_id}.tmp.XXXXXX")"
  trap '[[ -z "${staging:-}" ]] || rm -rf "${staging}"' RETURN
  tar --no-same-owner --no-same-permissions -xzf "${archive}" -C "${staging}"
  chmod 0755 "${staging}"
  printf '%s\n' "${release_id}" >"${staging}/.foundation-release-id"
  printf '%s\n' "${archive_sha}" >"${staging}/.foundation-release-archive-sha256"
  mv "${staging}" "${target}"
  staging=""
  trap - RETURN
  activate_release "${release_id}"
}

rollback_release() {
  local previous_target previous_id current_target
  prepare_mutable_state
  [[ -L "${release_root}/previous" ]] || {
    printf 'no previous release is available\n' >&2
    exit 66
  }
  previous_target="$(readlink "${release_root}/previous")"
  [[ "${previous_target}" =~ ^releases/([0-9a-f]{40})$ ]] || {
    printf 'previous release link is invalid: %s\n' "${previous_target}" >&2
    exit 65
  }
  previous_id="${BASH_REMATCH[1]}"
  assert_installed_release "${previous_id}"
  current_target="$(readlink "${release_root}/current")"
  atomic_link "${previous_target}" "${release_root}/current"
  atomic_link "${current_target}" "${release_root}/previous"
}

verify_runtime_schema() {
  # Deploying source cannot move the schema: the migrations are compiled into the runtime image
  # by `sqlx::migrate!`. On 2026-09-01 that gap was six weeks and thirty-three-minus-four
  # migrations wide, with every catalog table empty and the API answering `[]`, and no step
  # anywhere compared the two. This is that step.
  local checker="${release_root}/current/scripts/deploy/assert-runtime-migrations.sh"
  [[ -x "${checker}" ]] || {
    printf 'runtime migration check is missing from the release: %s\n' "${checker}" >&2
    exit 66
  }
  local environment="${release_root}/current/scripts/deploy/assert-runtime-environment.sh"
  [[ -x "${environment}" ]] || {
    printf 'runtime environment check is missing from the release: %s\n' "${environment}" >&2
    exit 66
  }
  # The environment first. A variable the compose files require and the host does not carry
  # surfaces as an interpolation error in the middle of a migration run — after the image
  # rebuild, with nothing having said beforehand that the file was behind. Measured 2026-09-01
  # while repairing the schema gap: six variables were missing, and compose named one per
  # attempt, so the hole looked two deep until the whole file was compared (root ADR-0071).
  "${environment}" "${release_root}/current"
  "${checker}" "${release_root}/current"
}

migrate_runtime() {
  # Rebuild before applying. The migrator is the release's own binary and the migrations live
  # inside it, so an image built from an older tree applies an older set however new the source
  # on disk is — which is exactly how the runtime came to be six weeks behind.
  local runtime="${release_root}/current/scripts/deploy/foundation-runtime.sh"
  [[ -x "${runtime}" ]] || {
    printf 'runtime compose wrapper is missing from the release: %s\n' "${runtime}" >&2
    exit 66
  }
  "${runtime}" build foundation-api
  # Asks for the end state, and names no step on the way to it.
  #
  # The compose file already declares the order — postgres, bootstrap, migrate, grants,
  # finalize, api — each link a `service_completed_successfully`. This used to run
  # `up --no-deps postgres` and then `run foundation-migrate`, which is that chain written a
  # second time and stopped in the middle. On 2026-09-02 the consequence surfaced: the database
  # had every migration and the API answered `permission denied for schema catalog`, because
  # `foundation-runtime-grants` never ran. Nothing said so — `/health` does not touch the
  # database, so the stack looked up for a day.
  #
  # `foundation-api` is the last link, so requiring it requires all of them, in the order the
  # compose file owns. `--wait` makes the command finish when the state is reached rather than
  # when the request was accepted.
  "${runtime}" up -d --wait foundation-api
  # The identity loopback sidecars are asked for separately, and not redundantly: they depend
  # on foundation-api, and compose only pulls dependencies in the direction of the arrow —
  # asking for the api alone leaves its own loopback listeners down, which surfaced on the
  # first identity bring-up as policy calls dying inside a healthy-looking container.
  "${runtime}" up -d --wait identity-zitadel-loopback identity-api-loopback
  verify_runtime_schema
}

status() {
  printf 'release_root=%s\n' "${release_root}"
  printf 'state_root=%s\n' "${state_root}"
  printf 'current=%s\n' "$(readlink "${release_root}/current" 2>/dev/null || true)"
  printf 'previous=%s\n' "$(readlink "${release_root}/previous" 2>/dev/null || true)"
}

command="${1:-}"
case "${command}" in
  install)
    [[ "$#" == 3 ]] || usage
    install_release "$2" "$3"
    # A deploy that leaves the running schema behind has not finished, and saying otherwise is
    # what let the runtime sit six weeks and twenty-nine migrations behind while three deploys
    # reported success. The release is installed and activated by this point, so the operator
    # can run `migrate` — this refuses to call the deploy done, it does not undo it.
    verify_runtime_schema
    ;;
  activate)
    [[ "$#" == 2 ]] || usage
    require_release_id "$2"
    mkdir -p "${releases_dir}" "${state_root}/recovery"
    prepare_mutable_state
    activate_release "$2"
    ;;
  migrate)
    [[ "$#" == 1 ]] || usage
    migrate_runtime
    ;;
  verify)
    [[ "$#" == 1 ]] || usage
    verify_runtime_schema
    ;;
  timers)
    # The release installs and enables its own systemd timers (root ADR-0077). The unit files
    # ship inside the release, so "which timers exist" has exactly one home; installing them by
    # hand is how the backup timer's install steps and the deployed tree drifted apart before.
    # Idempotent: reinstalling the same files and re-enabling an enabled timer are no-ops.
    [[ "$#" == 1 || "$#" == 2 ]] || usage
    install -o root -g root -m 0644 \
      -t /etc/systemd/system \
      "${release_root}/current/infra/systemd/foundation-postgres-backup.service" \
      "${release_root}/current/infra/systemd/foundation-postgres-backup.timer" \
      "${release_root}/current/infra/systemd/foundation-source-sweep.service" \
      "${release_root}/current/infra/systemd/foundation-outbox-publish.service" \
      "${release_root}/current/infra/systemd/foundation-map-edit-fold@.service" \
      "${release_root}/current/infra/systemd/foundation-lineage-stewardship.service"
    # The fold was one complex-only unit before it became a per-unit template; a host upgraded
    # from then still carries it, and it would fold complex a second time every hour.
    if [[ -e /etc/systemd/system/foundation-map-edit-fold.timer ]]; then
      systemctl disable --now foundation-map-edit-fold.timer || true
      rm -f /etc/systemd/system/foundation-map-edit-fold.timer \
        /etc/systemd/system/foundation-map-edit-fold.service
    fi
    # A job Airflow runs (orchestration/jobs.v1.json `enabled`) loses its timer in the release that
    # switches its DAG on (root ADR-0122 §4), so it runs in exactly one place. Its service stays:
    # systemd still runs it, Airflow only starts it.
    jobs_file="${release_root}/current/orchestration/jobs.v1.json"
    while read -r timer; do
      [[ -n "${timer}" ]] || continue
      if [[ -e "/etc/systemd/system/${timer}" ]]; then
        systemctl disable --now "${timer}" || true
        rm -f "/etc/systemd/system/${timer}"
        printf 'timer retired to airflow: %s\n' "${timer}"
      fi
    done < <(python3 -c '
import json, sys
for job in json.load(open(sys.argv[1]))["jobs"]:
    if job["enabled"]:
        print(job["systemd_timer"])
' "${jobs_file}")
    install_scheduler_access "${jobs_file}" "${2:-}"
    # Working directories the fold and the stewardship cycle write, whoever starts them.
    install -d -o foundation-platform -g foundation-platform \
      /var/lib/foundation-platform/map-edit-fold /var/lib/foundation-platform/lineage-stewardship
    systemctl daemon-reload
    # The database backup is host infrastructure, not a data job: it stays a systemd timer
    # (root ADR-0118 §1). Every data job is started by Airflow (root ADR-0122).
    systemctl enable --now foundation-postgres-backup.timer
    printf 'timers-ok backup=%s\n' "$(systemctl is-enabled foundation-postgres-backup.timer)"
    ;;
  rollback)
    [[ "$#" == 1 ]] || usage
    rollback_release
    ;;
  status)
    [[ "$#" == 1 ]] || usage
    status
    ;;
  *) usage ;;
esac
