#!/usr/bin/env python3
"""Renders one ODCS v3 data contract per lakehouse table from the two sources that own the facts
(root ADR-0123).

- columns, types, required, allowed values, quality gates: the Rust lakehouse contracts, read from
  their checked export platforms/foundation-platform/infra/lakehouse/contracts/
  industrial_complex_lakehouse_contracts.json
- name, description, owner, declared status, upstream datasets: the pipeline graph,
  platforms/foundation-platform/docs/catalog/pipeline-graph.v1.json

The output files are generated; never edit them. `--check` fails when they differ from what this
renders (the guard data-contracts-are-generated runs it).
"""

import argparse
import json
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parents[2]
PLATFORM = ROOT / "platforms" / "foundation-platform"
LAKEHOUSE_CONTRACTS = PLATFORM / "infra" / "lakehouse" / "contracts" / "industrial_complex_lakehouse_contracts.json"
GRAPH = PLATFORM / "docs" / "catalog" / "pipeline-graph.v1.json"
OUTPUT = PLATFORM / "contracts" / "data"
API_VERSION = "v3.2.0"
HEADER = (
    "# Generated by scripts/catalog/render-data-contracts.py from the Rust lakehouse contracts and the\n"
    "# pipeline graph (root ADR-0123). Do not edit: change the source and re-render.\n"
)
# ODCS status for the graph's declared status; the declared value is kept in customProperties.
STATUS = {"implemented": "active", "contract_only": "draft", "planned": "proposed"}
# ODCS logical types. A physical type ODCS has no logical word for (binary geometry) keeps only
# its physicalType rather than being called something it is not.
LOGICAL = {
    "string": "string",
    "timestamp": "timestamp",
    "date": "date",
    "boolean": "boolean",
    "int": "integer",
    "long": "integer",
    "double": "number",
}


class RenderError(ValueError):
    pass


def logical_type(physical):
    if physical in LOGICAL:
        return LOGICAL[physical]
    if re.fullmatch(r"decimal\(\d+,\d+\)", physical):
        return "number"
    if physical.startswith("array<"):
        return "array"
    if physical == "binary":
        return None
    raise RenderError(f"no ODCS logical type for {physical!r}; add it to LOGICAL deliberately")


def documents_for(lakehouse, graph):
    """One ODCS document (a dict) per lakehouse table, keyed by output file name."""
    nodes_by_table = {node["table_name"]: node for node in graph["nodes"] if node.get("table_name")}
    nodes = {node["id"]: node for node in graph["nodes"]}
    tables = lakehouse["contracts"]
    only_rust = sorted(set(tables) - set(nodes_by_table))
    only_graph = sorted(set(nodes_by_table) - set(tables))
    if only_rust or only_graph:
        raise RenderError(
            f"the two sources disagree on the lakehouse tables: only in the Rust contracts {only_rust}, "
            f"only in the pipeline graph {only_graph}"
        )
    domains = lakehouse.get("value_domains", {})
    rendered = {}
    for table, contract in sorted(tables.items()):
        node = nodes_by_table[table]
        if node["status"] not in STATUS:
            raise RenderError(f"{table}: declared status {node['status']!r} has no ODCS status")
        upstream = sorted(
            nodes[edge["from"]].get("table_name") or edge["from"]
            for edge in graph["edges"]
            if edge["to"] == node["id"]
        )
        allowed = domains.get(table, {})
        properties = []
        for column in contract["columns"]:
            prop = {"name": column["name"], "physicalType": column["logical_type"]}
            logical = logical_type(column["logical_type"])
            if logical:
                prop["logicalType"] = logical
            prop["required"] = bool(column["required"])
            if column["name"] in contract.get("partition_spec", []):
                prop["partitioned"] = True
                prop["partitionKeyPosition"] = contract["partition_spec"].index(column["name"]) + 1
            if column["name"] in allowed:
                prop["enum"] = [{"value": value} for value in allowed[column["name"]]]
            properties.append(prop)
        document = {
            "apiVersion": API_VERSION,
            "kind": "DataContract",
            "id": table,
            "name": node["title"],
            "version": "1.0.0",
            "status": STATUS[node["status"]],
            "domain": "foundation-platform",
            "description": {"purpose": node["description"]},
            "team": {"name": node["owner"]},
            "schema": [
                {
                    "name": table,
                    "physicalName": table,
                    "logicalType": "object",
                    "physicalType": "table",
                    "properties": properties,
                    "quality": [
                        {"type": "text", "description": gate} for gate in contract.get("quality_gates", [])
                    ],
                }
            ],
            "customProperties": [
                {"property": "pipelineGraphNode", "value": node["id"]},
                {"property": "declaredStatus", "value": node["status"]},
                {"property": "servingRole", "value": contract["serving_role"]},
                {"property": "physicalFormat", "value": contract["physical_format"]},
                {"property": "sortOrder", "value": contract.get("sort_order", [])},
                {"property": "upstreamDatasets", "value": upstream},
            ],
        }
        if not document["schema"][0]["quality"]:
            del document["schema"][0]["quality"]
        rendered[f"{table}.odcs.yaml"] = document
    return rendered


def contracts_for(lakehouse, graph):
    return {name: HEADER + to_yaml(document) for name, document in documents_for(lakehouse, graph).items()}


def scalar(value):
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (int, float)):
        return json.dumps(value)
    if value is None:
        return "null"
    # A JSON string is a valid YAML double-quoted scalar.
    return json.dumps(str(value), ensure_ascii=False)


def to_yaml(value, indent=0):
    pad = "  " * indent
    lines = []
    if isinstance(value, dict):
        for key, item in value.items():
            if isinstance(item, (dict, list)) and item:
                lines.append(f"{pad}{key}:")
                lines.append(to_yaml(item, indent + 1).rstrip("\n"))
            elif isinstance(item, list):
                lines.append(f"{pad}{key}: []")
            elif isinstance(item, dict):
                lines.append(f"{pad}{key}: {{}}")
            else:
                lines.append(f"{pad}{key}: {scalar(item)}")
    elif isinstance(value, list):
        for item in value:
            if isinstance(item, dict) and item:
                inner = to_yaml(item, indent + 1).rstrip("\n").split("\n")
                lines.append(f"{pad}- {inner[0].lstrip()}")
                lines.extend(inner[1:])
            elif isinstance(item, list) and item:
                lines.append(f"{pad}-")
                lines.append(to_yaml(item, indent + 1).rstrip("\n"))
            else:
                lines.append(f"{pad}- {scalar(item)}")
    return "\n".join(lines) + "\n"


def main():
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true", help="fail when the committed files differ")
    args = parser.parse_args()
    lakehouse = json.loads(LAKEHOUSE_CONTRACTS.read_text(encoding="utf-8"))
    graph = json.loads(GRAPH.read_text(encoding="utf-8"))
    try:
        rendered = contracts_for(lakehouse, graph)
    except RenderError as error:
        sys.exit(f"FAIL data-contracts: {error}")

    existing = {path.name for path in OUTPUT.glob("*.odcs.yaml")} if OUTPUT.is_dir() else set()
    if args.check:
        stale = sorted(
            name for name, text in rendered.items()
            if not (OUTPUT / name).is_file() or (OUTPUT / name).read_text(encoding="utf-8") != text
        )
        orphans = sorted(existing - set(rendered))
        if stale or orphans:
            for name in stale:
                print(f"FAIL data-contracts: {name} differs from its sources; run {pathlib.Path(__file__).name}", file=sys.stderr)
            for name in orphans:
                print(f"FAIL data-contracts: {name} has no table in the sources", file=sys.stderr)
            sys.exit(1)
        print(f"OK data-contracts: {len(rendered)} contract(s) match their sources")
        return
    OUTPUT.mkdir(parents=True, exist_ok=True)
    for name in existing - set(rendered):
        (OUTPUT / name).unlink()
    for name, text in rendered.items():
        (OUTPUT / name).write_text(text, encoding="utf-8", newline="\n")
    print(f"rendered {len(rendered)} data contract(s) into {OUTPUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
