"""`complex_id` is pinned to values this repository did not compute.

Every expected value below was produced by CPython's `uuid.uuid5(uuid.NAMESPACE_URL, seed)`
and then written down. They are literals on purpose: an expectation generated by the code
under test agrees with that code by construction and catches nothing, which is how a
derivation that was never a version-5 UUID reached `r2.silver.industrial_complexes`
(ADR-0043).

Coverage is over the RFC 4122 variant nibble, not over rows. The old rule shifted octet 8
instead of masking it, so it produced the right answer for a quarter of all digests by
accident: seed suffix `000002` below is one of those. `VariantNibbleCoverageTest` fails if
the vector set stops covering all four of `8`/`9`/`a`/`b`.
"""

import sys
import unittest
from pathlib import Path


JOBS_DIR = Path(__file__).resolve().parents[1] / "jobs"
sys.path.insert(0, str(JOBS_DIR))

# A module-level PySpark import here would make this whole file unrunnable in CI, which is
# the state the derivation shipped in. The import below is the check that it stays runnable.
from industrial_complex_bronze_to_silver import (  # noqa: E402
    COMPLEX_ID_SEED_PREFIX,
    complex_id_seed,
    stable_uuid_v5_string,
)


# suffix of `official_complex_code` -> uuid.uuid5(NAMESPACE_URL, COMPLEX_ID_SEED_PREFIX + suffix)
RFC4122_VECTORS: tuple[tuple[str, str], ...] = (
    ("000000", "b796bcb0-f180-5220-8007-4cf27bf4c87b"),
    ("000001", "20c71d10-9b9a-5e7a-95fc-0ffa834b3867"),
    ("000004", "5c146e9d-ae48-5a99-a63d-05318a68fae8"),
    ("000002", "f2d96c8f-4733-5946-bf5b-5e8b1320abf6"),
    ("111010", "7df3859c-768f-51fa-a78d-6398acd5f052"),
    ("111011", "c00ffadd-4196-5a0b-a8a1-c203cf78b434"),
    ("445010", "0072ba44-d5c2-50e8-829c-87741ad04f81"),
)

# What the pre-ADR-0043 rule actually wrote to `r2.silver.industrial_complexes` for three real
# industrial-complex codes. Same digest, one nibble apart, and lowercase-UUID shaped -- so the
# `complex_id must be a lowercase UUID string` gate passed every one of them. Only a join
# against an independently derived id would have gone to zero.
SUPERSEDED_VALUES: tuple[tuple[str, str], ...] = (
    ("111010", "7df3859c-768f-51fa-978d-6398acd5f052"),
    ("111011", "c00ffadd-4196-5a0b-98a1-c203cf78b434"),
    ("445010", "0072ba44-d5c2-50e8-929c-87741ad04f81"),
)


def variant_nibble(uuid_text: str) -> str:
    return uuid_text.split("-")[3][0]


def version_nibble(uuid_text: str) -> str:
    return uuid_text.split("-")[2][0]


class ComplexIdSeedTest(unittest.TestCase):
    def test_seed_prefix_is_the_one_the_published_ids_were_derived_from(self) -> None:
        self.assertEqual(
            COMPLEX_ID_SEED_PREFIX, "foundation-platform:catalog:industrial_complex:"
        )

    def test_seed_is_the_prefix_followed_by_the_official_code(self) -> None:
        self.assertEqual(
            complex_id_seed("111010"),
            "foundation-platform:catalog:industrial_complex:111010",
        )


class StableUuidV5Test(unittest.TestCase):
    def test_derivation_matches_the_standard_library_vectors(self) -> None:
        for suffix, expected in RFC4122_VECTORS:
            with self.subTest(official_complex_code=suffix):
                self.assertEqual(stable_uuid_v5_string(complex_id_seed(suffix)), expected)

    def test_derivation_no_longer_produces_the_superseded_values(self) -> None:
        for suffix, superseded in SUPERSEDED_VALUES:
            with self.subTest(official_complex_code=suffix):
                self.assertNotEqual(
                    stable_uuid_v5_string(complex_id_seed(suffix)), superseded
                )

    def test_a_seed_that_is_null_stays_null(self) -> None:
        # `official_complex_code` is required, so a null seed is a Bronze defect. It is the
        # `complex_id must not be null` gate's job to say so, per row and with samples.
        self.assertIsNone(stable_uuid_v5_string(None))


class VariantNibbleCoverageTest(unittest.TestCase):
    """RFC 4122 4.1.1 keeps the low two bits of octet 8, so the nibble is one of four."""

    def test_the_vectors_cover_every_variant_nibble(self) -> None:
        self.assertEqual(
            {variant_nibble(expected) for _, expected in RFC4122_VECTORS},
            {"8", "9", "a", "b"},
        )

    def test_every_vector_is_version_five(self) -> None:
        for suffix, expected in RFC4122_VECTORS:
            with self.subTest(official_complex_code=suffix):
                self.assertEqual(version_nibble(expected), "5")


if __name__ == "__main__":
    unittest.main()
