/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/catalog/v1/buildings/by-register-pk/{register_pk}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getBuildingByRegisterPk"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/catalog/v1/buildings/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getBuilding"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/catalog/v1/buildings/{id}/units": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listBuildingUnits"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/catalog/v1/complexes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listComplexes"];
        put?: never;
        post: operations["registerComplex"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/catalog/v1/complexes/by-lakehouse-id/{lakehouse_complex_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getComplexByLakehouseId"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/catalog/v1/complexes/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getComplex"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["updateComplex"];
        trace?: never;
    };
    "/catalog/v1/complexes/{id}/anchor-summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getComplexAnchorSummary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/catalog/v1/complexes/{id}/archive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["archiveComplex"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/catalog/v1/complexes/{id}/attachments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listComplexAttachments"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/catalog/v1/complexes/{id}/blueprints": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listComplexBlueprints"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/catalog/v1/complexes/{id}/digital-twin-assets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listComplexDigitalTwinAssets"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/catalog/v1/complexes/{id}/notices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listComplexNotices"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/catalog/v1/complexes/{id}/spatial-layers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listComplexSpatialLayers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/catalog/v1/industry-groups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listIndustryGroups"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/catalog/v1/lakehouse/batch-runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["recordLakehouseBatchRun"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/catalog/v1/map-edits/{unit}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["appendMapEdit"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/catalog/v1/parcel-marker-anchors:rebuild": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["rebuildParcelMarkerAnchors"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/catalog/v1/parcels/by-pnu/{pnu}/buildings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listParcelBuildingsByPnu"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/catalog/v1/parcels/by-pnu/{pnu}/units": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listParcelUnitsByPnu"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/catalog/v1/parcels/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getParcel"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/catalog/v1/parcels/{id}/industry-assignments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listParcelIndustryAssignments"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/catalog/v1/parcels/{id}/kind": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["updateParcelKind"];
        trace?: never;
    };
    "/catalog/v1/vector-tiles/manifest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getVectorTileManifest"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/catalog/v1/vector-tiles/manifest:promote": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["promoteVectorTileManifest"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/catalog/v1/vector-tiles/manifest:rollback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["rollbackVectorTileManifest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/catalog/v1/vector-tiles/runtime-manifest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Returns the atomic v2 runtime manifest with a quoted `ETag` and conditional GET support. */
        get: operations["getVectorTileRuntimeManifest"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/map/v1/marker-tiles/contract": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getMarkerTileContract"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/map/v1/marker-tiles/{layer}/{z}/{x}/{y}.pbf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getMarkerTile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["metrics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ready"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Request body for archiving an industrial complex with optimistic concurrency. */
        ArchiveComplexRequest: {
            /**
             * Format: int64
             * @description Version observed by the caller; stale values return conflict.
             */
            if_match_version: number;
            /** @description Optional human-readable archive reason for audit. */
            reason?: string | null;
        };
        /** @description Blueprint or drawing metadata assigned to an industrial complex. */
        BlueprintResponse: {
            /** @description Blueprint kind. Wire values: `master_plan`, `parcel_map`, `utility_plan`, `floor_plan`, `other`. */
            blueprint_kind: string;
            /**
             * Format: uuid
             * @description Industrial complex that owns this blueprint.
             */
            complex_id: string;
            /** @description Coordinate reference system used by the drawing. */
            coordinate_system: string;
            /**
             * Format: uuid
             * @description File asset that stores the blueprint object.
             */
            file_asset_id: string;
            /**
             * Format: uuid
             * @description Stable foundation-platform identifier for the blueprint.
             */
            id: string;
            /** @description Optional scale label from the source drawing. */
            scale?: string | null;
            /**
             * Format: date-time
             * @description UTC timestamp of the last canonical Catalog update.
             */
            updated_at: string;
            /**
             * Format: int64
             * @description Monotonic record version used for optimistic concurrency.
             */
            version: number;
        };
        /** @description Canonical building response. */
        BuildingResponse: {
            /**
             * Format: int32
             * @description Number of below-ground (basement) floors. `0` when none or unknown.
             */
            below_ground_floors: number;
            /**
             * Format: int32
             * @description Construction-approval year from the official source. `null` when the register states
             *     no plausible date — never fabricated.
             */
            built_year?: number | null;
            /**
             * Format: double
             * @description Official floor area (연면적) in square meters. `null` when the register wrote 0 or
             *     nothing.
             */
            floor_area_m2?: number | null;
            /** @description Whether the building has a rooftop (옥탑) structure counted as a floor. */
            has_rooftop: boolean;
            /**
             * Format: uuid
             * @description Stable foundation-platform identifier for the building.
             */
            id: string;
            /**
             * Format: uuid
             * @description Parcel that owns this building.
             */
            parcel_id: string;
            /** @description Source building purpose code. `null` when the register stated nothing (ADR-0076 §1). */
            purpose_code?: string | null;
            /**
             * @description Natural key: the title-register record (관리대장 PK) this building was loaded from —
             *     the name a person calls the building by (ADR-0076 §2).
             */
            register_pk: string;
            /**
             * Format: double
             * @description 옥탑 공용부 allocated area (㎡) reconciled from 전유공용면적. `null` when the
             *     building has no rooftop.
             */
            rooftop_area_m2?: number | null;
            /**
             * @description 옥탑 용도 (주용도 · 기타용도) reconciled from 전유공용면적. Empty when the
             *     building has no rooftop.
             */
            rooftop_usage: string;
            /**
             * Format: int32
             * @description Number of above-ground stories. `null` when the register stated nothing.
             */
            stories?: number | null;
            /** @description Source building structure code. `null` when the register stated nothing. */
            structure_code?: string | null;
            /**
             * Format: date-time
             * @description UTC timestamp of the last canonical Catalog update.
             */
            updated_at: string;
        };
        /** @description Anchor-derived map summary for one industrial complex. */
        ComplexAnchorSummaryResponse: {
            /**
             * Format: int64
             * @description Number of active parcel anchors represented by this summary.
             */
            anchor_count: number;
            /**
             * Format: double
             * @description Average latitude of active parcel anchors in EPSG:4326.
             */
            center_lat: number;
            /**
             * Format: double
             * @description Average longitude of active parcel anchors in EPSG:4326.
             */
            center_lng: number;
            /**
             * Format: uuid
             * @description Industrial complex whose active parcel anchors were summarized.
             */
            complex_id: string;
            /**
             * Format: double
             * @description Maximum active anchor latitude in EPSG:4326.
             */
            max_lat: number;
            /**
             * Format: double
             * @description Maximum active anchor longitude in EPSG:4326.
             */
            max_lng: number;
            /**
             * Format: double
             * @description Minimum active anchor latitude in EPSG:4326.
             */
            min_lat: number;
            /**
             * Format: double
             * @description Minimum active anchor longitude in EPSG:4326.
             */
            min_lng: number;
            /** @description Canonical source for the summary coordinates. Current value: `pnu_anchor`. */
            position_source: string;
        };
        /** @description Official notice or announcement attached to an industrial complex. */
        ComplexNoticeResponse: {
            /** @description File attachments linked to the notice. */
            attachments: components["schemas"]["FileAssetResponse"][];
            /**
             * Format: uuid
             * @description Industrial complex that owns this notice.
             */
            complex_id: string;
            /**
             * Format: uuid
             * @description Stable foundation-platform identifier for the notice.
             */
            id: string;
            /** @description Notice type. Wire values: `notice`, `announcement`, `sale`, `regulation`, `maintenance`, `other`. */
            notice_type: string;
            /**
             * Format: date-time
             * @description Publication timestamp when the source provides one.
             */
            published_at?: string | null;
            /** @description Optional short summary prepared for list views. */
            summary?: string | null;
            /** @description Notice title. */
            title: string;
            /**
             * Format: date-time
             * @description UTC timestamp of the last canonical Catalog update.
             */
            updated_at: string;
            /**
             * Format: int64
             * @description Monotonic record version used for optimistic concurrency.
             */
            version: number;
        };
        /** @description Digital twin asset metadata assigned below an industrial complex. */
        DigitalTwinAssetResponse: {
            /** @description Asset kind. Wire values: `model_3d`, `tileset_3d`, `point_cloud`, `panorama`, `other`. */
            asset_kind: string;
            /**
             * Format: uuid
             * @description Optional building identifier when the asset represents a building.
             */
            building_id?: string | null;
            /**
             * Format: uuid
             * @description Industrial complex that owns this asset.
             */
            complex_id: string;
            /** @description Optional coordinate transform payload for renderer alignment. */
            coordinate_transform?: unknown;
            /**
             * Format: uuid
             * @description File asset that stores the 3D or visualization artifact.
             */
            file_asset_id: string;
            /**
             * Format: uuid
             * @description Stable foundation-platform identifier for the digital twin asset.
             */
            id: string;
            /**
             * Format: uuid
             * @description Optional parcel that narrows the asset scope.
             */
            parcel_id?: string | null;
            /**
             * Format: date-time
             * @description UTC timestamp of the last canonical Catalog update.
             */
            updated_at: string;
            /**
             * Format: int64
             * @description Monotonic record version used for optimistic concurrency.
             */
            version: number;
        };
        /** @description Provider-neutral file metadata owned by foundation-platform Catalog. */
        FileAssetResponse: {
            /** @description Optional SHA-256 checksum in lowercase hexadecimal form. */
            checksum_sha256?: string | null;
            /**
             * Format: uuid
             * @description Stable foundation-platform identifier for the file asset.
             */
            id: string;
            /** @description MIME type recorded for the object. */
            mime_type: string;
            /** @description Provider-neutral object storage key. This intentionally avoids S3/R2-specific naming. */
            object_key: string;
            /**
             * Format: int64
             * @description Object size in bytes.
             */
            size_bytes: number;
            /** @description Optional display title for UI surfaces. */
            title?: string | null;
            /**
             * Format: date-time
             * @description UTC timestamp of the last canonical Catalog update.
             */
            updated_at: string;
            /**
             * Format: int64
             * @description Monotonic record version used for optimistic concurrency.
             */
            version: number;
            /** @description File visibility. Wire values: `public`, `internal`, `private`. */
            visibility: string;
        };
        HealthResponse: {
            service: string;
            status: string;
            version: string;
        };
        /** @description Thin pointer to R2/Iceberg Gold industrial-complex data. */
        IndustrialComplexGoldPointerResponse: {
            /** @description Active Gold artifact version. */
            current_version: string;
            /** @description Iceberg snapshot id represented by the artifact. */
            iceberg_snapshot_id: string;
            /** @description Previously active Gold artifact version, when one existed. */
            previous_version?: string | null;
            /** @description SHA-256 checksum for the profile artifact. */
            profile_checksum_sha256: string;
            /** @description Provider-neutral object key for the Gold profile artifact. */
            profile_object_key: string;
            /**
             * Format: int64
             * @description Number of profile rows represented by the artifact.
             */
            profile_row_count: number;
            /**
             * @description Address template that turns either object key of this pointer into a fetchable URL.
             *
             *     Consumers substitute `{object_key}`; the pointer never carries a materialized URL so one
             *     template addresses both the profile and the optional spatial locator.
             */
            profile_url_template: string;
            /**
             * Format: date-time
             * @description UTC timestamp when the pointer was published.
             */
            published_at: string;
            /**
             * Format: uuid
             * @description Source record that describes the publish input.
             */
            source_record_id: string;
            /** @description Source snapshot represented by the artifact. */
            source_snapshot_id: string;
            /** @description Provider-neutral object key for the optional spatial locator artifact. */
            spatial_locator_object_key?: string | null;
        };
        /**
         * @description One page of canonical industrial complexes.
         *
         *     An envelope rather than a bare array because a page without its collection size is unreadable:
         *     a screen showing "20 of ?" cannot tell a filter that matched nothing from a filter it has not
         *     finished paging. `total` counts the rows the filters match, not the rows on this page.
         */
        IndustrialComplexListResponse: {
            /** @description Complexes on this page, in the requested order. */
            complexes: components["schemas"]["IndustrialComplexResponse"][];
            /** @description Whether a further page exists behind `total`. */
            has_next: boolean;
            /**
             * Format: int32
             * @description Zero-indexed page number that was served.
             */
            page: number;
            /**
             * Format: int32
             * @description Page size that was served.
             */
            size: number;
            /**
             * Format: int64
             * @description Complexes the filters match in total.
             */
            total: number;
        };
        /** @description Canonical industrial complex response owned by foundation-platform Catalog. */
        IndustrialComplexResponse: {
            /**
             * @description Address the source stated for the complex.
             *
             *     One complex spans many legal divisions and sometimes several provinces, so this is the
             *     source's own wording rather than anything reconstructed from the codes above.
             */
            address_text?: string | null;
            /**
             * Format: date-time
             * @description UTC timestamp when the complex was archived, if no longer active.
             */
            archived_at?: string | null;
            /**
             * Format: int64
             * @description Official complex area in square meters.
             */
            area_m2: number;
            /** @description Last month of `business_period_raw` as `YYYY-MM`, when that text parses. */
            business_period_end_month?: string | null;
            /** @description Business period exactly as the source wrote it, normally `YYYY-MM~YYYY-MM`. */
            business_period_raw?: string | null;
            /**
             * @description First month of `business_period_raw` as `YYYY-MM`, when that text parses.
             *
             *     Null together with `business_period_end_month`. One complex's source period states years
             *     without months, and for it both are null while `business_period_raw` still carries the text.
             */
            business_period_start_month?: string | null;
            /**
             * Format: date
             * @description Date the complex's site formation was approved as complete, as `YYYY-MM-DD`.
             */
            completion_date?: string | null;
            /**
             * Format: date
             * @description Date site works started, as `YYYY-MM-DD`.
             */
            construction_start_date?: string | null;
            /**
             * Format: date
             * @description Date the complex was officially designated, as `YYYY-MM-DD`.
             */
            designated_date?: string | null;
            /** @description Statute the designation was made under, in the source's own words. */
            designation_basis_law_raw?: string | null;
            /** @description Organization that developed the complex. */
            developer_name?: string | null;
            /**
             * @description Development method, in the source's own words.
             *
             *     Free text, and the `_raw` suffix says so: the source spells one method several ways and
             *     nothing here folds them together, because that would assert a classification the source
             *     never published.
             */
            development_method_raw?: string | null;
            /**
             * @description Site-formation progress as an exact decimal percentage between `0.00` and `100.00`.
             *
             *     A string, not a number: the canonical column is `numeric(5,2)` and a JSON number is a
             *     double for most clients, which cannot hold `59.9`. The text is the exact value the source
             *     stated. `0.00` is a real answer — site works that have not started — and is not the same as
             *     `null`, which means the source stated no progress at all.
             */
            development_progress_percent?: string | null;
            /** @description Stated purpose the complex was developed for, in the source's own words. */
            development_purpose_raw?: string | null;
            gold_pointer?: null | components["schemas"]["IndustrialComplexGoldPointerResponse"];
            /**
             * Format: uuid
             * @description Stable foundation-platform identifier for the complex.
             */
            id: string;
            /** @description Industry types the complex set out to attract, in the source's own words. */
            invited_industries_raw?: string | null;
            /** @description Industrial complex kind as a public wire value. */
            kind: string;
            /**
             * @description The source's own words for `kind` (for example `농공`), trimmed and otherwise verbatim.
             *
             *     Show these to people; filter on the codes. Several source words can share one code, and
             *     only these fields say which the source stated. `null` when the complex has no source row
             *     (registered through this API) or was loaded before the words were kept.
             */
            kind_raw?: string | null;
            /**
             * Format: uuid
             * @description Identifier the same complex carries in the lakehouse, when it was sourced from there.
             *
             *     Unrelated to `id`: that one is minted locally, this one is derived and is what Gold
             *     artifact object keys are computed from. A client that wants the complex's Gold profile
             *     object needs this value, not `id`. `null` for a complex registered through this API.
             */
            lakehouse_complex_id?: string | null;
            /**
             * @description How far the complex has got in selling or leasing its lots.
             *
             *     Wire values: `planned`, `in_progress`, `completed`. Independent of `status`, which is about
             *     building the complex: a complex can be `operating` with lots still on sale.
             */
            lot_sales_status?: string | null;
            /** @description The source's own words for `lot_sales_status` (for example `분양계획`). */
            lot_sales_status_raw?: string | null;
            /** @description Organization that manages the complex. */
            management_agency_name?: string | null;
            /** @description Human-readable industrial complex name. */
            name: string;
            /** @description Source-side official industrial-complex code. */
            official_complex_code: string;
            /**
             * @description primary legal-dong code shared by parcels that belong to the complex.
             *
             *     `null` for every complex sourced from the Gold catalog: that projection resolves addresses
             *     to sigungu granularity at best, so no legal-dong code exists to publish (root ADR-0040).
             */
            primary_bjdong_code?: string | null;
            /** @description Province-level administrative code, when one was sourced. */
            sido_code?: string | null;
            /** @description City/county/district administrative code, when one was sourced. */
            sigungu_code?: string | null;
            /**
             * @description Where the complex is in its development lifecycle.
             *
             *     Wire values: `planned`, `developing`, `operating`, `changed`, `abolished`, `unknown`.
             *     `unknown` and `null` are different answers — `unknown` means the source stated a lifecycle
             *     this contract does not recognize, `null` means it stated none.
             */
            status?: string | null;
            /**
             * @description The source's own words for `status` (for example `보상중`, which shares `planned` with
             *     `준비중`).
             */
            status_raw?: string | null;
            /**
             * Format: date-time
             * @description UTC timestamp of the last canonical Catalog update.
             */
            updated_at: string;
            /**
             * Format: int64
             * @description Monotonic record version used for optimistic concurrency.
             */
            version: number;
        };
        /** @description Single industry code inside an industry group. */
        IndustryGroupMemberResponse: {
            /** @description Industry code value, for example a KSIC code. */
            industry_code: string;
            /** @description Industry code system. Currently `ksic`. */
            industry_code_system: string;
        };
        /** @description Industry grouping allowed or recommended inside an industrial complex. */
        IndustryGroupResponse: {
            /**
             * Format: uuid
             * @description Industrial complex that owns this industry group.
             */
            complex_id: string;
            /** @description Optional source-provided description. */
            description?: string | null;
            /**
             * Format: uuid
             * @description Stable foundation-platform identifier for the industry group.
             */
            id: string;
            /** @description Industry code members that make up the group. */
            members: components["schemas"]["IndustryGroupMemberResponse"][];
            /** @description Display name of the industry group. */
            name: string;
            /**
             * Format: date-time
             * @description UTC timestamp of the last canonical Catalog update.
             */
            updated_at: string;
            /**
             * Format: int64
             * @description Monotonic record version used for optimistic concurrency.
             */
            version: number;
        };
        /**
         * @description Manufacturer read response that deliberately omits sensitive business identifiers.
         *
         *     No route returns this today: the complex-scoped manufacturer list was deleted rather than
         *     migrated to the membership table, because nothing called it (ADR-0021). The shape is kept
         *     because its field list *is* a decision — `business_registration_number` is on the domain type
         *     and deliberately absent here — and that decision would be silently lost if the type went with
         *     the route. A future manufacturer read starts from this shape rather than re-deciding it.
         */
        ManufacturerResponse: {
            /**
             * Format: uuid
             * @description Stable foundation-platform identifier for the manufacturer.
             */
            id: string;
            /** @description Korean Standard Industrial Classification code. */
            ksic_code: string;
            /** @description Manufacturer display name. */
            name: string;
            /**
             * Format: uuid
             * @description Primary parcel occupied by the manufacturer.
             */
            primary_parcel_id: string;
            /**
             * Format: date-time
             * @description UTC timestamp of the last canonical Catalog update.
             */
            updated_at: string;
        };
        /**
         * @description An administrator's polygon edit, shown to customers before the next bake folds it into the
         *     tiles (root ADR-0112).
         */
        MapEditRequest: {
            /** @description The feature id the unit's tiles carry, e.g. a `complex_id`. */
            feature_id: string;
            /**
             * @description `GeoJSON` `Polygon` or `MultiPolygon` in EPSG:4326; required for `upsert`, absent for
             *     `delete`.
             */
            geometry?: Record<string, never> | null;
            /** @description Retry identity: the same key with the same edit is answered, not repeated. */
            idempotency_key: string;
            /** @description `upsert` (replace or add the polygon) or `delete` (remove it from the map). */
            op: string;
            /** @description The unit's public tile properties; required for `upsert`, absent for `delete`. */
            properties?: Record<string, never> | null;
        };
        /** @description The edit store's answer for a saved edit. */
        MapEditResponse: {
            /**
             * Format: int64
             * @description The store's order for the edit; bakes fold edits through this sequence.
             */
            change_seq: number;
            /** @description Whether this answers an earlier request with the same idempotency key. */
            replayed: boolean;
            /** @description The publication unit the edit belongs to. */
            unit: string;
        };
        /** @description Public contract for PNU-anchor backed marker tile endpoints. */
        MarkerTileContractResponse: {
            /**
             * Format: int32
             * @description Highest zoom level served by aggregate anchor artifacts.
             */
            aggregate_anchor_max_zoom: number;
            /** @description Public launch marker requests must not be based on arbitrary bbox inputs. */
            bbox_marker_runtime_forbidden: boolean;
            /** @description Database-backed reference endpoint must not be treated as the launch hot path. */
            db_reference_endpoint_launch_forbidden: boolean;
            /** @description Intended scope for the database-backed marker endpoint. */
            db_reference_endpoint_scope: string;
            /** @description Default filter identity for the supported anchor layer. */
            default_filter_hash: string;
            /** @description Successful marker responses must not silently drop eligible records. */
            dropped_marker_success_forbidden: boolean;
            /** @description Canonical marker tile endpoint shape. */
            endpoint_template: string;
            /**
             * Format: int32
             * @description Lowest zoom level where exact parcel anchors may be requested.
             */
            exact_anchor_min_zoom: number;
            /** @description Canonical launch runtime for static marker tiles. */
            launch_runtime_source: string;
            /** @description Canonical source for marker positions. Current value: `pnu_anchor`. */
            position_source: string;
            /** @description Wire response format for map-wide marker surfaces. Current value: `mvt_pbf`. */
            response_format: string;
            /** @description Runtime manifest endpoint consumed before clients materialize tile URLs. */
            runtime_manifest_endpoint: string;
            /** @description Marker layers currently supported by the public tile endpoint. */
            supported_layers: string[];
        };
        /** @description One parcel's newest cadastral characteristics (root ADR-0087). */
        ParcelCharacteristicResponse: {
            /**
             * Format: double
             * @description Official cadastral area in square meters.
             */
            area_m2: number;
            /** @description Cadastral land category name exactly as the source wrote it. */
            land_category?: string | null;
            /** @description Land-use situation name exactly as the source wrote it. */
            land_use_situation?: string | null;
            /** @description Road-contact name exactly as the source wrote it. */
            road_contact?: string | null;
            /** @description Terrain height name exactly as the source wrote it. */
            terrain_height?: string | null;
            /** @description Terrain shape name exactly as the source wrote it. */
            terrain_shape?: string | null;
        };
        /** @description One forest parcel's newest official ledger facts. */
        ParcelForestLedgerResponse: {
            /**
             * Format: double
             * @description Official ledger area in square meters.
             */
            area_m2?: number | null;
            /**
             * Format: int32
             * @description Number of co-owners recorded by the provider.
             */
            co_owner_count?: number | null;
            /** @description Cadastral land category name exactly as the provider wrote it. */
            land_category?: string | null;
            /** @description Provider ownership category code, not an owner identity. */
            ownership_kind?: string | null;
        };
        /** @description Assignment between a parcel and an industry group. */
        ParcelIndustryAssignmentResponse: {
            /** @description Assignment kind. Wire values: `allowed`, `recommended`, `restricted`. */
            assignment_kind: string;
            /**
             * Format: uuid
             * @description Stable foundation-platform identifier for the assignment.
             */
            id: string;
            /**
             * Format: uuid
             * @description Industry group assigned to the parcel.
             */
            industry_group_id: string;
            /**
             * Format: uuid
             * @description Parcel receiving this assignment.
             */
            parcel_id: string;
            /**
             * Format: date-time
             * @description UTC timestamp of the last canonical Catalog update.
             */
            updated_at: string;
            /**
             * Format: int64
             * @description Monotonic record version used for optimistic concurrency.
             */
            version: number;
        };
        /** @description One unit-level land right from the Foundation Catalog. */
        ParcelLandRightResponse: {
            /** @description Building name, unchanged. */
            building_name?: string | null;
            /** @description Provider closure kind name, unchanged. */
            closure_kind?: string | null;
            /** @description Provider closure kind code, unchanged. */
            closure_kind_code?: string | null;
            /** @description Building dong designation; empty when the provider row leaves it blank (root ADR-0093). */
            dong_name?: string;
            /** @description Floor designation; empty when the provider row leaves it blank. */
            floor_name?: string;
            /** @description Ho designation; empty when the provider row leaves it blank. */
            ho_name?: string;
            /** @description Provider land-right ratio, preserved verbatim. */
            right_ratio?: string | null;
            /** @description Provider row serial number, preserved verbatim. */
            right_serial_no: string;
            /** @description Room designation; empty when the provider row leaves it blank. */
            room_name?: string;
        };
        /** @description Request body for rebuilding parcel marker anchors from an approved mirror snapshot. */
        ParcelMarkerAnchorRebuildRequest: {
            /** @description Stable algorithm implementation version. */
            algorithm_version: string;
            /** @description Approved Iceberg snapshot represented by the `PostGIS` mirror rows. */
            source_snapshot_id: string;
        };
        /** @description Response body returned after a parcel marker anchor rebuild finishes. */
        ParcelMarkerAnchorRebuildResponse: {
            /** @description Anchor derivation algorithm. */
            algorithm: string;
            /** @description Stable algorithm implementation version. */
            algorithm_version: string;
            /**
             * Format: uuid
             * @description Generation run persisted for traceability.
             */
            generation_run_id: string;
            /**
             * Format: int64
             * @description Anchor rows inserted or updated.
             */
            loaded_row_count: number;
            /**
             * Format: int64
             * @description Mirror rows rejected before writing anchors.
             */
            rejected_row_count: number;
            /**
             * Format: int64
             * @description Mirror rows inspected for this snapshot.
             */
            scanned_row_count: number;
            /** @description Approved Iceberg snapshot represented by the rebuild. */
            source_snapshot_id: string;
            /** @description Canonical source table represented by the rebuild. */
            source_table: string;
            /**
             * Format: int64
             * @description Previously active anchors superseded for the same PNUs.
             */
            superseded_row_count: number;
        };
        /**
         * @description One parcel's newest official land price assessment (root ADR-0085).
         *
         *     Foundation carries the source's integers verbatim; formatting money and interpreting the
         *     announcement date are the consumer's decisions.
         */
        ParcelPriceResponse: {
            /** @description Announcement date (공시일자) exactly as the source wrote it. Absent when blank. */
            announced_date?: string | null;
            /**
             * Format: int32
             * @description Assessment base month (기준월), 1–12.
             */
            base_month: number;
            /**
             * Format: int32
             * @description Assessment base year (기준연도).
             */
            base_year: number;
            /**
             * Format: int64
             * @description Official land price in won per square meter, the source's integer unchanged.
             */
            price_per_m2: number;
        };
        /**
         * @description Canonical parcel response.
         *
         *     Carries no industrial complex. Membership is a dated fact between two entities rather than a
         *     property of the parcel (ADR-0019), and most parcels belong to no complex at all.
         */
        ParcelResponse: {
            /**
             * Format: int64
             * @description Official parcel area in square meters.
             *
             *     Absent until a source carrying the cadastral area is collected. Not derived from the
             *     boundary polygon: a measured area is a different fact (root ADR-0020).
             */
            area_m2?: number | null;
            /**
             * Format: uuid
             * @description Stable foundation-platform identifier for the parcel.
             */
            id: string;
            /**
             * @description Parcel kind. Wire values: `factory`, `support`, `public`, `river`, `other`.
             *
             *     Absent until a person decides one. The vocabulary describes land use inside an
             *     industrial complex and most parcels belong to none (root ADR-0070).
             */
            kind?: string | null;
            /** @description Parcel Number Unit identifier. */
            pnu: string;
            /**
             * Format: date-time
             * @description UTC timestamp of the last canonical Catalog update.
             */
            updated_at: string;
            /**
             * Format: int64
             * @description Monotonic record version used for optimistic concurrency.
             */
            version: number;
        };
        /** @description One raw cadastral transfer event from the Foundation Catalog. */
        ParcelTransferEventResponse: {
            /**
             * Format: double
             * @description Official parcel area at the time of the event.
             */
            area_m2?: number | null;
            /** @description Provider closure sequence, unchanged. */
            closure_seq?: string | null;
            /** @description Erasure date exactly as the provider wrote it. */
            erased_at?: string | null;
            /**
             * Format: int64
             * @description Provider event sequence within the parcel.
             */
            history_seq: number;
            /** @description Cadastral land category at the time of the event. */
            land_category?: string | null;
            /** @description Transfer date exactly as the provider wrote it. */
            moved_at?: string | null;
            /** @description 토지이력순번 — disambiguates events sharing one `history_seq` (root ADR-0090). */
            parcel_history_seq: string;
            /** @description Provider transfer reason, unchanged. */
            reason?: string | null;
            /** @description Provider transfer reason code, unchanged. */
            reason_code?: string | null;
        };
        /**
         * @description One land-use zoning verdict on a parcel (root ADR-0083).
         *
         *     Foundation carries the LMIS code and its resolved anchor; translating the anchor into a
         *     product vocabulary is the consumer's decision.
         */
        ParcelZoningResponse: {
            /**
             * @description Code-tree anchor the zone resolved to: `UQA100` 주거, `UQA200` 상업, `UQA300` 공업,
             *     `UQA400` 녹지, `UQA001` 도시 미세분, `UQB001` 관리, `UQC001` 농림, `UQD001` 자연환경보전.
             */
            anchor_code: string;
            /** @description `1` 포함 or `2` 저촉 — 접함 never enters the projection. */
            inclusion_code: string;
            /** @description LMIS zone code exactly as the plan ledger stated it (e.g. `UQA320`). */
            zone_code: string;
            /** @description Korean zone name the source shipped, untranslated. Absent when the source was blank. */
            zone_name?: string | null;
        };
        /** @description File asset payload supplied during vector tile manifest promote. */
        PromoteFileAssetRequest: {
            /** @description Optional SHA-256 checksum in lowercase hexadecimal form. */
            checksum_sha256?: string | null;
            /** @description MIME type recorded for the object. */
            mime_type: string;
            /** @description Provider-neutral object storage key. This intentionally avoids S3/R2-specific naming. */
            object_key: string;
            /**
             * Format: int64
             * @description Object size in bytes.
             */
            size_bytes: number;
            /** @description Optional display title for UI surfaces. */
            title?: string | null;
            /** @description File visibility. Wire values: `public`, `internal`, `private`. */
            visibility: string;
        };
        /** @description Source record payload supplied during vector tile manifest promote. */
        PromoteSourceRecordRequest: {
            /** @description Optional SHA-256 checksum in lowercase hexadecimal form. */
            checksum_sha256?: string | null;
            /** @description Optional source-side identifier. */
            external_id?: string | null;
            /** @description Optional provider-neutral object key for the raw source artifact. */
            raw_object_key?: string | null;
            /** @description Source system or pipeline name. */
            source: string;
            /** @description Optional source URL for traceability. */
            source_url?: string | null;
        };
        /** @description Per-layer artifact payload supplied during vector tile manifest promote. */
        PromoteVectorTileArtifactRequest: {
            /**
             * Format: int64
             * @description Number of flat tile objects generated for this layer.
             */
            flat_tile_count: number;
            /**
             * Format: int64
             * @description Total bytes across flat tile objects for this layer.
             */
            flat_tile_total_bytes: number;
            /** @description Provider-neutral prefix that contains this layer's tile objects. */
            object_key_prefix: string;
            /**
             * Format: int32
             * @description Maximum zoom level where clients should render the layer.
             */
            render_max_zoom: number;
            /**
             * Format: int32
             * @description Minimum zoom level where clients should render the layer.
             */
            render_min_zoom: number;
            /** @description Source file assets used to build this layer. */
            source_file_assets: components["schemas"]["PromoteFileAssetRequest"][];
            /** @description Source layer name embedded in the vector tile payload. */
            source_layer: string;
            /**
             * Format: int32
             * @description Maximum zoom level available in stored tiles.
             */
            tile_max_zoom: number;
            /**
             * Format: int32
             * @description Minimum zoom level available in stored tiles.
             */
            tile_min_zoom: number;
            /** @description File asset metadata for this layer's `TileJSON` document. */
            tilejson_file_asset: components["schemas"]["PromoteFileAssetRequest"];
        };
        /** @description Request body for promoting a vector tile build into the active manifest slot. */
        PromoteVectorTileManifestRequest: {
            /** @description Layer artifacts keyed by logical layer name. */
            artifacts: {
                [key: string]: components["schemas"]["PromoteVectorTileArtifactRequest"];
            };
            /** @description Version that should become active after promote. */
            current_version: string;
            /** @description Active version the caller expects before promote. */
            expected_current_version: string;
            /** @description File asset metadata for the manifest JSON artifact. */
            manifest_file_asset: components["schemas"]["PromoteFileAssetRequest"];
            /** @description Source record describing the build input. */
            source_record: components["schemas"]["PromoteSourceRecordRequest"];
            /** @description Immutable Gold/Iceberg snapshot that produced this tile build. */
            source_snapshot_id: string;
            /** @description URL template clients use to request vector tiles. */
            tiles_url_template: string;
        };
        ReadinessResponse: {
            database: string;
            /** @description How many shipped migrations the database is missing. Zero when `schema` is not `behind`. */
            migrations_missing: number;
            /** @description `ok`, `behind`, or `unknown` — whether the database holds every shipped migration. */
            schema: string;
            service: string;
            status: string;
            version: string;
        };
        /** @description Request body for registering an industrial complex. */
        RegisterComplexRequest: {
            /**
             * Format: int64
             * @description Official complex area in square meters.
             */
            area_m2: number;
            /** @description Industrial complex kind. Wire values: `national`, `general`, `agricultural`, `urban_high_tech`. */
            kind: string;
            /** @description Human-readable industrial complex name. */
            name: string;
            /** @description Source-side official industrial-complex code. */
            official_complex_code: string;
            /** @description primary legal-dong code shared by parcels that belong to the complex, when one is known. */
            primary_bjdong_code?: string | null;
        };
        /** @description Request body for manually rolling back the active vector tile manifest. */
        RollbackVectorTileManifestRequest: {
            /** @description Active version the caller expects before rollback. */
            expected_current_version: string;
            /** @description Human-readable rollback reason for audit logs. */
            reason: string;
            /** @description Version that should become active after rollback. */
            to_version: string;
        };
        /** @description Geospatial layer metadata assigned below an industrial complex. */
        SpatialLayerResponse: {
            /**
             * Format: uuid
             * @description Optional blueprint that the layer overlays.
             */
            blueprint_id?: string | null;
            /**
             * Format: uuid
             * @description Industrial complex that owns this layer.
             */
            complex_id: string;
            /** @description Optional object key for the geometry artifact. */
            geometry_object_key?: string | null;
            /**
             * Format: uuid
             * @description Stable foundation-platform identifier for the spatial layer.
             */
            id: string;
            /** @description Layer kind. Wire values: `complex_boundary`, `parcel_boundary`, `zone`, `road`, `utility`, `blueprint_overlay`, `other`. */
            layer_kind: string;
            /**
             * Format: uuid
             * @description Optional parcel that narrows the layer scope.
             */
            parcel_id?: string | null;
            /**
             * Format: date-time
             * @description UTC timestamp of the last canonical Catalog update.
             */
            updated_at: string;
            /**
             * Format: int64
             * @description Monotonic record version used for optimistic concurrency.
             */
            version: number;
        };
        /** @description One reference-date official assessment of a registered unit. */
        UnitOfficialPriceResponse: {
            /** @description Assessment reference date in YYYYMMDD format. */
            base_date: string;
            /**
             * Format: int64
             * @description Official assessed value in won.
             */
            price_won: number;
        };
        /**
         * @description One keyset page of a building's units (ADR-0076 §3).
         *
         *     Born paginated: a single building holds up to 5,372 measured units, and a list that grows
         *     with the resource must never be an unbounded array. `next_cursor` is opaque — a caller
         *     passes it back verbatim and never parses it.
         */
        UnitPageResponse: {
            /** @description The page of units, ordered `(dong_name, ho_name, id)`. */
            items: components["schemas"]["UnitResponse"][];
            /** @description Cursor for the next page; `null` when this page is the last. */
            next_cursor?: string | null;
        };
        /** @description Canonical 전유부 호 (building unit) response for a parcel. */
        UnitResponse: {
            /**
             * Format: uuid
             * @description Building this unit hangs in (ADR-0074). `null` when the register's own link was
             *     unresolved or the building is absent from the catalog — hiding it would claim every
             *     unit is linked, which is not what was measured (ADR-0076 §4).
             */
            building_id?: string | null;
            /** @description 건물명 (normalized building name, may be empty). */
            building_name: string;
            /** @description 동명칭 — only real 동 numbers; empty otherwise. */
            dong_name: string;
            /**
             * Format: double
             * @description 전유면적 (exclusive area, m²), reconciled from 전유공용면적. `null` when unmatched.
             */
            exclusive_area_m2?: number | null;
            /** @description Floor label (지상/지하 + number), free text from source. */
            floor_label: string;
            /** @description 호명칭. */
            ho_name: string;
            /**
             * Format: uuid
             * @description Stable foundation-platform identifier for the unit.
             */
            id: string;
            /** @description Reference-date official assessments, newest first; empty when no price matches this unit. */
            official_price_history?: components["schemas"]["UnitOfficialPriceResponse"][];
            /**
             * Format: uuid
             * @description Parcel that owns this unit.
             */
            parcel_id: string;
            /** @description 구조명, reconciled from 전유공용면적. Empty when unmatched. */
            structure_name: string;
            /** @description 주용도명, reconciled from 전유공용면적. Empty when unmatched. */
            usage_name: string;
        };
        /** @description Request body for updating canonical industrial-complex metadata with optimistic concurrency. */
        UpdateComplexRequest: {
            /**
             * Format: int64
             * @description Optional replacement official complex area in square meters.
             */
            area_m2?: number | null;
            /**
             * Format: int64
             * @description Version observed by the caller; stale values return conflict.
             */
            if_match_version: number;
            /** @description Optional replacement human-readable industrial complex name. */
            name?: string | null;
        };
        /** @description Request body for updating a parcel kind with optimistic concurrency. */
        UpdateParcelKindRequest: {
            /**
             * Format: int64
             * @description Version observed by the caller; stale values return conflict.
             */
            if_match_version: number;
            /** @description New parcel kind wire value. */
            new_kind: string;
        };
        /** @description Per-layer vector tile artifact metadata inside the runtime manifest. */
        VectorTileArtifactResponse: {
            /** @description Logical filter properties mapped to concrete feature property names in the vector tile. */
            feature_filter_properties?: {
                [key: string]: string;
            };
            /**
             * Format: int64
             * @description Number of flat tile objects generated for this layer.
             */
            flat_tile_count: number;
            /**
             * Format: int64
             * @description Total bytes across flat tile objects for this layer.
             */
            flat_tile_total_bytes: number;
            /** @description Source and file lineage that produced this artifact. */
            lineage: components["schemas"]["VectorTileLineageResponse"];
            /** @description Provider-neutral prefix that contains this layer's tile objects. */
            object_key_prefix: string;
            /**
             * Format: int32
             * @description Maximum zoom level where clients should render the layer.
             */
            render_max_zoom: number;
            /**
             * Format: int32
             * @description Minimum zoom level where clients should render the layer.
             */
            render_min_zoom: number;
            /** @description Source layer name embedded in the vector tile payload. */
            source_layer: string;
            /**
             * Format: int32
             * @description Maximum zoom level available in stored tiles.
             */
            tile_max_zoom: number;
            /**
             * Format: int32
             * @description Minimum zoom level available in stored tiles.
             */
            tile_min_zoom: number;
            /** @description Provider-neutral object key for this layer's `TileJSON` document. */
            tilejson_object_key: string;
        };
        /** @description Dynamic `PostGIS` source response. */
        VectorTileDynamicPostgisResponse: {
            /** @description Must be `no_store` for the dynamic source. */
            cache_policy: string;
            /** @description Stable configured Martin source name. */
            martin_source_id: string;
            /** @description Complete Martin tile URL template. */
            tiles_url_template: string;
        };
        /** @description Lineage links required to audit a vector tile artifact. */
        VectorTileLineageResponse: {
            /**
             * Format: uuid
             * @description File asset row for the manifest JSON file.
             */
            manifest_file_asset_id: string;
            /** @description File asset rows for source files used to build the layer. */
            source_file_asset_ids: string[];
            /**
             * Format: uuid
             * @description Source record that describes the tile build input.
             */
            source_record_id: string;
            /**
             * Format: uuid
             * @description File asset row for the layer `TileJSON` file.
             */
            tilejson_file_asset_id: string;
        };
        /** @description Runtime vector tile manifest consumed by Gongzzang map surfaces. */
        VectorTileManifestResponse: {
            /** @description Layer artifacts keyed by logical layer name, for example `parcels`. */
            artifacts: {
                [key: string]: components["schemas"]["VectorTileArtifactResponse"];
            };
            /** @description Active tile artifact version. */
            current_version: string;
            /** @description Previously active tile artifact version retained for rollback awareness. */
            previous_version: string;
            /**
             * Format: date-time
             * @description UTC timestamp when this manifest became active.
             */
            published_at: string;
            /**
             * Format: int32
             * @description Manifest schema version.
             */
            schema_version: number;
            /** @description Immutable Gold/Iceberg snapshot that produced this tile build. */
            source_snapshot_id: string;
            /** @description URL template for vector tile requests. */
            tiles_url_template: string;
        };
        /** @description One v2 publication unit response. */
        VectorTilePublicationUnitResponse: {
            /**
             * Format: uuid
             * @description Immutable release descriptor UUID.
             */
            active_release_id: string;
            /** @description Positive decimal Iceberg snapshot id represented by the unit. */
            canonical_iceberg_snapshot_id: string;
            /**
             * Format: uuid
             * @description UUID of the logical feature set.
             */
            data_revision: string;
            /** @description MVT layers served by this source. */
            layers: {
                [key: string]: components["schemas"]["VectorTileRuntimeLayerResponse"];
            };
            /** @description Source lineage. */
            lineage: components["schemas"]["VectorTileRuntimeLineageResponse"];
            /**
             * Format: int64
             * @description JavaScript-safe source selection generation.
             */
            serving_generation: number;
            /** @description Exactly one complete Martin source. */
            source: components["schemas"]["VectorTileRuntimeSourceResponse"];
        };
        /** @description Layer metadata in a v2 runtime source. */
        VectorTileRuntimeLayerResponse: {
            /** @description Concrete feature properties used by client filters. */
            feature_filter_properties: {
                [key: string]: string;
            };
            /** @description Canonical lower-case feature identity property. */
            feature_id_property: string;
            /**
             * Format: int32
             * @description Client render maximum zoom.
             */
            render_max_zoom: number;
            /**
             * Format: int32
             * @description Client render minimum zoom.
             */
            render_min_zoom: number;
            /** @description MVT source layer name. */
            source_layer: string;
            /**
             * Format: int32
             * @description Stored tile maximum zoom.
             */
            tile_max_zoom: number;
            /**
             * Format: int32
             * @description Stored tile minimum zoom.
             */
            tile_min_zoom: number;
        };
        /** @description Lineage metadata in a v2 runtime source. */
        VectorTileRuntimeLineageResponse: {
            /** @description Source file asset UUIDs. */
            source_file_asset_ids: string[];
            /**
             * Format: uuid
             * @description Source record UUID.
             */
            source_record_id: string;
        };
        /** @description Foundation-owned v2 runtime manifest response. */
        VectorTileRuntimeManifestResponse: {
            /**
             * Format: uuid
             * @description Immutable manifest UUID and `ETag` identity.
             */
            current_version: string;
            /**
             * Format: int64
             * @description Global JavaScript-safe poll generation.
             */
            manifest_generation: number;
            /** @description Non-empty atomically switched publication units. */
            publication_units: {
                [key: string]: components["schemas"]["VectorTilePublicationUnitResponse"];
            };
            /**
             * Format: date-time
             * @description UTC publication timestamp.
             */
            published_at: string;
            /**
             * Format: int32
             * @description Required bounded polling interval.
             */
            refresh_after_seconds: number;
            /**
             * Format: int32
             * @description Exact manifest schema version. Always `2`.
             */
            schema_version: number;
        };
        /** @description Closed v2 source union. */
        VectorTileRuntimeSourceResponse: (components["schemas"]["VectorTileDynamicPostgisResponse"] & {
            /** @enum {string} */
            kind: "dynamic_postgis";
        }) | (components["schemas"]["VectorTileStaticPmtilesResponse"] & {
            /** @enum {string} */
            kind: "static_pmtiles";
        });
        /** @description Immutable `PMTiles` source response. */
        VectorTileStaticPmtilesResponse: {
            /** @description Release-addressed Martin source name. */
            martin_source_id: string;
            /**
             * Format: int64
             * @description `PMTiles` object size in bytes.
             */
            pmtiles_bytes: number;
            /**
             * Format: uuid
             * @description File asset UUID for the `PMTiles` object.
             */
            pmtiles_file_asset_id: string;
            /** @description Immutable `PMTiles` object key. */
            pmtiles_object_key: string;
            /** @description Lowercase SHA-256 checksum. */
            pmtiles_sha256: string;
            /** @description Complete Martin tile URL template. */
            tiles_url_template: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getBuildingByRegisterPk: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Title-register PK (관리대장 PK), the building's natural key */
                register_pk: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BuildingResponse"];
                };
            };
            /** @description Building not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getBuilding: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Building id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BuildingResponse"];
                };
            };
            /** @description Building not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listBuildingUnits: {
        parameters: {
            query?: {
                /** @description Page size, 1..=1000 (default 200) */
                limit?: number;
                /** @description Opaque cursor from the previous page's next_cursor */
                cursor?: string;
            };
            header?: never;
            path: {
                /** @description Building id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnitPageResponse"];
                };
            };
            /** @description Building not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listComplexes: {
        parameters: {
            query?: {
                /** @description Substring of the complex name or official complex code */
                q?: string;
                /** @description Two-digit province code */
                sido_code?: string;
                /** @description Comma-separated development lifecycle filter: planned, developing, operating, changed, abolished, unknown */
                status?: string;
                /** @description Zero-indexed page number (default 0) */
                page?: number;
                /** @description Page size (default 20, maximum 100) */
                size?: number;
                /** @description name_asc (default) | area_desc | official_complex_code_asc */
                sort?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IndustrialComplexListResponse"];
                };
            };
            /** @description A search parameter was outside the served bounds */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    registerComplex: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterComplexRequest"];
            };
        };
        responses: {
            /** @description Industrial complex registered */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IndustrialComplexResponse"];
                };
            };
        };
    };
    getComplexByLakehouseId: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Lakehouse industrial-complex id (UUIDv5), as published in Gold artifact keys and `complex` vector tile feature ids */
                lakehouse_complex_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IndustrialComplexResponse"];
                };
            };
            /** @description No canonical complex carries that lakehouse id */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getComplex: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Industrial complex id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IndustrialComplexResponse"];
                };
            };
        };
    };
    updateComplex: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Industrial complex id */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateComplexRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IndustrialComplexResponse"];
                };
            };
        };
    };
    getComplexAnchorSummary: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Industrial complex id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ComplexAnchorSummaryResponse"];
                };
            };
        };
    };
    archiveComplex: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Industrial complex id */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ArchiveComplexRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IndustrialComplexResponse"];
                };
            };
        };
    };
    listComplexAttachments: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Industrial complex id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FileAssetResponse"][];
                };
            };
        };
    };
    listComplexBlueprints: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Industrial complex id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BlueprintResponse"][];
                };
            };
        };
    };
    listComplexDigitalTwinAssets: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Industrial complex id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DigitalTwinAssetResponse"][];
                };
            };
        };
    };
    listComplexNotices: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Industrial complex id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ComplexNoticeResponse"][];
                };
            };
        };
    };
    listComplexSpatialLayers: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Industrial complex id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpatialLayerResponse"][];
                };
            };
        };
    };
    listIndustryGroups: {
        parameters: {
            query?: {
                /** @description Optional industrial complex filter */
                complex_id?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IndustryGroupResponse"][];
                };
            };
        };
    };
    recordLakehouseBatchRun: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": unknown;
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    appendMapEdit: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Polygon publication unit, e.g. complex */
                unit: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MapEditRequest"];
            };
        };
        responses: {
            /** @description The same idempotency key and edit were already saved */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MapEditResponse"];
                };
            };
            /** @description Saved; customers see it on their next overlay read */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MapEditResponse"];
                };
            };
            /** @description Idempotency key reused for a different edit, or the unit needs a bake first */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The edit is invalid: operation, topology, bounds, id or properties */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The edit store is not configured or not reachable; nothing was saved */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    rebuildParcelMarkerAnchors: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ParcelMarkerAnchorRebuildRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ParcelMarkerAnchorRebuildResponse"];
                };
            };
        };
    };
    listParcelBuildingsByPnu: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 19-digit Parcel Number Unit */
                pnu: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BuildingResponse"][];
                };
            };
        };
    };
    listParcelUnitsByPnu: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 19-digit Parcel Number Unit */
                pnu: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnitResponse"][];
                };
            };
        };
    };
    getParcel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Parcel id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ParcelResponse"];
                };
            };
            /** @description Parcel not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listParcelIndustryAssignments: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Parcel id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ParcelIndustryAssignmentResponse"][];
                };
            };
        };
    };
    updateParcelKind: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Parcel id */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateParcelKindRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ParcelResponse"];
                };
            };
        };
    };
    getVectorTileManifest: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VectorTileManifestResponse"];
                };
            };
            /** @description Active manifest not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    promoteVectorTileManifest: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PromoteVectorTileManifestRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VectorTileManifestResponse"];
                };
            };
        };
    };
    rollbackVectorTileManifest: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RollbackVectorTileManifestRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VectorTileManifestResponse"];
                };
            };
        };
    };
    getVectorTileRuntimeManifest: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VectorTileRuntimeManifestResponse"];
                };
            };
            304: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description v2 runtime manifest is disabled or not published */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service process is alive */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    getMarkerTileContract: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MarkerTileContractResponse"];
                };
            };
        };
    };
    getMarkerTile: {
        parameters: {
            query: {
                filter_hash: string;
            };
            header?: never;
            path: {
                layer: string;
                z: number;
                x: number;
                y: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/x-protobuf": number[];
                };
            };
        };
    };
    metrics: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Prometheus metrics */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
        };
    };
    ready: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service dependencies are ready */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadinessResponse"];
                };
            };
            /** @description Service dependencies are unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadinessResponse"];
                };
            };
        };
    };
}
