/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/data-catalog/v1/entity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Reads one entity with its columns and one step of lineage either way. */
        get: operations["getDataCatalogEntity"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/data-catalog/v1/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Finds datasets by name or description. */
        get: operations["searchDataCatalog"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Safe error body returned by Foundation API handlers. */
        ApiErrorResponse: {
            /** @description Safe client-facing diagnostic. */
            error: string;
        };
        /** @description One entity as a list, a search result or a graph node shows it. */
        DataCatalogEntity: {
            /** @description What it is, in the words its owner wrote. */
            description?: string | null;
            /** @description Dataset or job. */
            kind: components["schemas"]["DataCatalogEntityKind"];
            /** @description The name people know it by. */
            name: string;
            /** @description The system it lives in, when the catalog records one. */
            platform?: string | null;
            /** @description The catalog's identifier; pass it back unchanged to read the entity or its neighbours. */
            urn: string;
        };
        /**
         * @description What kind of thing a catalog entity is.
         * @enum {string}
         */
        DataCatalogEntityKind: "dataset" | "job";
        /** @description One column of a dataset. */
        DataCatalogField: {
            /** @description What the column holds. */
            description?: string | null;
            /** @description Type as the catalog records it. */
            native_type?: string | null;
            /** @description Column path. */
            path: string;
        };
        /**
         * @description An entity and the entities one step before and after it.
         *
         *     A dataset's neighbours are the jobs that write and read it; a job's neighbours are the datasets
         *     it reads and writes. A screen walks the graph by asking for a neighbour's neighbours.
         */
        DataCatalogNeighbourhood: {
            /** @description What comes from it. */
            downstream: components["schemas"]["DataCatalogEntity"][];
            /** @description The entity asked about. */
            entity: components["schemas"]["DataCatalogEntity"];
            /** @description Its columns, for a dataset whose schema the catalog holds. */
            fields: components["schemas"]["DataCatalogField"][];
            /** @description What it comes from. */
            upstream: components["schemas"]["DataCatalogEntity"][];
        };
        /** @description One page of search results. */
        DataCatalogSearchPage: {
            /** @description Results on this page, best match first. */
            results: components["schemas"]["DataCatalogEntity"][];
            /**
             * Format: int32
             * @description Zero-based offset of the first result on this page.
             */
            start: number;
            /**
             * Format: int32
             * @description Entities the query matches in total, not just on this page.
             */
            total: number;
        };
        /** @description Opaque internal-error body returned by Foundation API handlers. */
        InternalApiErrorResponse: {
            /**
             * Format: uuid
             * @description Opaque identifier operators can use to locate an internal failure.
             */
            correlation_id: string;
            /** @description Stable opaque diagnostic. */
            error: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getDataCatalogEntity: {
        parameters: {
            query: {
                /** @description The entity's `urn`, exactly as a search result or a neighbour gave it. */
                urn: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataCatalogNeighbourhood"];
                };
            };
            /** @description No staff identity */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Principal may not read the data catalog */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No such entity */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description The data catalog is not configured or not reachable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    searchDataCatalog: {
        parameters: {
            query?: {
                /** @description Words to find in names and descriptions; `*` or empty lists everything. */
                q?: string;
                /** @description Zero-based offset of the first result. */
                start?: number;
                /** @description Results per page, 1 to 50 (default 20). */
                count?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataCatalogSearchPage"];
                };
            };
            /** @description A page size outside 1..=50 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description No staff identity */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Principal may not read the data catalog */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The data catalog is not configured or not reachable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
}
