/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/data-catalog/v1/entity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Reads one entity with its columns and one step of lineage either way. */
        get: operations["getDataCatalogEntity"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/data-catalog/v1/quality-checks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Every data contract the catalog holds and the latest result of each of its checks. */
        get: operations["listDataQualityChecks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/data-catalog/v1/scheduled-jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Every scheduled job, its next start and its latest run. */
        get: operations["listScheduledJobs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/data-catalog/v1/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Finds datasets by name or description. */
        get: operations["searchDataCatalog"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Safe error body returned by Foundation API handlers. */
        ApiErrorResponse: {
            /** @description Safe client-facing diagnostic. */
            error: string;
        };
        /** @description One entity as a list, a search result or a graph node shows it. */
        DataCatalogEntity: {
            /** @description What it is, in the words its owner wrote. */
            description?: string | null;
            /** @description Dataset or job. */
            kind: components["schemas"]["DataCatalogEntityKind"];
            /** @description The name people know it by. */
            name: string;
            /** @description The system it lives in, when the catalog records one. */
            platform?: string | null;
            /** @description The catalog's identifier; pass it back unchanged to read the entity or its neighbours. */
            urn: string;
        };
        /**
         * @description What kind of thing a catalog entity is.
         * @enum {string}
         */
        DataCatalogEntityKind: "dataset" | "job";
        /** @description One column of a dataset. */
        DataCatalogField: {
            /** @description What the column holds. */
            description?: string | null;
            /** @description Type as the catalog records it. */
            native_type?: string | null;
            /** @description Column path. */
            path: string;
        };
        /**
         * @description An entity and the entities one step before and after it.
         *
         *     A dataset's neighbours are the jobs that write and read it; a job's neighbours are the datasets
         *     it reads and writes. A screen walks the graph by asking for a neighbour's neighbours.
         */
        DataCatalogNeighbourhood: {
            /** @description What comes from it. */
            downstream: components["schemas"]["DataCatalogEntity"][];
            /** @description The entity asked about. */
            entity: components["schemas"]["DataCatalogEntity"];
            /** @description Its columns, for a dataset whose schema the catalog holds. */
            fields: components["schemas"]["DataCatalogField"][];
            /** @description What it comes from. */
            upstream: components["schemas"]["DataCatalogEntity"][];
        };
        /** @description One page of search results. */
        DataCatalogSearchPage: {
            /** @description Results on this page, best match first. */
            results: components["schemas"]["DataCatalogEntity"][];
            /**
             * Format: int32
             * @description Zero-based offset of the first result on this page.
             */
            start: number;
            /**
             * Format: int32
             * @description Entities the query matches in total, not just on this page.
             */
            total: number;
        };
        /** @description One data contract and the latest result of each of its checks. */
        DataContractQuality: {
            /** @description Its checks. */
            checks: components["schemas"]["DataQualityCheck"][];
            /** @description The contract's id (the dataset it promises). */
            contract_id: string;
            /** @description The contract's entity in the data catalog. */
            dataset_urn: string;
        };
        /** @description One check a data contract defines and its latest result. */
        DataQualityCheck: {
            /** @description The check's identifier in the data catalog. */
            assertion_urn: string;
            /**
             * Format: date-time
             * @description When that result was reported.
             */
            checked_at?: string | null;
            /** @description What the job reported with it (counts, missing columns), as it wrote them. */
            details: components["schemas"]["DataQualityDetail"][];
            /** @description The column it checks, for a column check. */
            field?: string | null;
            /** @description The catalog's kind for it (for example `FIELD` or `DATA_SCHEMA`), as the catalog names it. */
            kind: string;
            /** @description Its latest result. */
            result: components["schemas"]["DataQualityResult"];
        };
        /** @description One key and value the quality job reported with a result. */
        DataQualityDetail: {
            /** @description The key, as the job wrote it. */
            key: string;
            /** @description The value, as the job wrote it. */
            value: string;
        };
        /**
         * @description The latest result of a data-quality check.
         * @enum {string}
         */
        DataQualityResult: "success" | "failure" | "error" | "not_run";
        /** @description Every data contract the data catalog holds, with its checks' latest results. */
        DataQualityStatus: {
            /** @description The contracts, by id. */
            contracts: components["schemas"]["DataContractQuality"][];
            /**
             * Format: date-time
             * @description When Foundation read this.
             */
            read_at: string;
        };
        /** @description Opaque internal-error body returned by Foundation API handlers. */
        InternalApiErrorResponse: {
            /**
             * Format: uuid
             * @description Opaque identifier operators can use to locate an internal failure.
             */
            correlation_id: string;
            /** @description Stable opaque diagnostic. */
            error: string;
        };
        /** @description The latest run of a scheduled job that the data catalog holds. */
        ScheduledJobRun: {
            /**
             * Format: date-time
             * @description When the run completed; absent while it runs.
             */
            finished_at?: string | null;
            /** @description The scheduler's own word for the result, as it sent it, when it sent one. */
            native_result?: string | null;
            /** @description How it stands. */
            outcome: components["schemas"]["ScheduledJobRunOutcome"];
            /** @description The run's identifier in the data catalog. */
            run_urn: string;
            /**
             * Format: date-time
             * @description When the run started, from its first recorded start.
             */
            started_at?: string | null;
        };
        /**
         * @description How a scheduled job's run stands, in the run record the scheduler sent to the data catalog
         *     (`OpenLineage`, root ADR-0118 §2): started and not yet complete, or complete with a result.
         * @enum {string}
         */
        ScheduledJobRunOutcome: "running" | "succeeded" | "failed" | "skipped" | "up_for_retry" | "unknown";
        /** @description One scheduled job: what the job list says about it and its latest run. */
        ScheduledJobStatus: {
            /** @description The job's entity in the data catalog that holds the latest run, once a run reported. */
            catalog_job_urn?: string | null;
            /** @description The scheduler's name for the job (its Airflow DAG). */
            dag_id: string;
            /** @description What the job does, as the job list says. */
            description: string;
            /** @description Why it is off and what turns it on, for a job that is off. */
            disabled_reason?: string | null;
            /** @description Whether the scheduler runs it. */
            enabled: boolean;
            /** @description The job's id in the job list (`orchestration/jobs.v1.json`). */
            job_id: string;
            last_run?: null | components["schemas"]["ScheduledJobRun"];
            /**
             * Format: date-time
             * @description The next time its schedule starts it; absent for a job that is off.
             */
            next_run_at?: string | null;
            /** @description When it runs: the job list's cron schedule, in UTC. */
            schedule: string;
        };
        /** @description Every scheduled job and its latest run. */
        ScheduledJobsStatus: {
            /** @description Every job in the job list, in its order. */
            jobs: components["schemas"]["ScheduledJobStatus"][];
            /**
             * Format: date-time
             * @description When Foundation read this.
             */
            read_at: string;
            /**
             * @description Why the runs could not be read, when the data catalog did not answer. The jobs are still
             *     listed, and then no job's missing run means it never ran.
             */
            run_history_error?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getDataCatalogEntity: {
        parameters: {
            query: {
                /** @description The entity's `urn`, exactly as a search result or a neighbour gave it. */
                urn: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataCatalogNeighbourhood"];
                };
            };
            /** @description No staff identity */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Principal may not read the data catalog */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No such entity */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description The data catalog is not configured or not reachable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    listDataQualityChecks: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataQualityStatus"];
                };
            };
            /** @description No staff identity */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Principal may not read the data catalog */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The data catalog is not configured or not reachable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    listScheduledJobs: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScheduledJobsStatus"];
                };
            };
            /** @description No staff identity */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Principal may not read the data catalog */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The job list could not be read */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InternalApiErrorResponse"];
                };
            };
        };
    };
    searchDataCatalog: {
        parameters: {
            query?: {
                /** @description Words to find in names and descriptions; `*` or empty lists everything. */
                q?: string;
                /** @description Zero-based offset of the first result. */
                start?: number;
                /** @description Results per page, 1 to 50 (default 20). */
                count?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataCatalogSearchPage"];
                };
            };
            /** @description A page size outside 1..=50 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description No staff identity */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Principal may not read the data catalog */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The data catalog is not configured or not reachable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
}
