/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/catalog/v1/lineage-review/decisions/{id}/approval": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["rule_on_decision"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/catalog/v1/lineage-review/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_items"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/catalog/v1/lineage-review/items/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_item"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/catalog/v1/lineage-review/items/{id}/claim": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["claim_item"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/catalog/v1/lineage-review/items/{id}/decisions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["decide_item"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/catalog/v1/lineage-review/items/{id}/release": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["release_item"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Safe error body returned by Foundation API handlers. */
        ApiErrorResponse: {
            /** @description Safe client-facing diagnostic. */
            error: string;
        };
        /** @description Opaque internal-error body returned by Foundation API handlers. */
        InternalApiErrorResponse: {
            /**
             * Format: uuid
             * @description Opaque identifier operators can use to locate an internal failure.
             */
            correlation_id: string;
            /** @description Stable opaque diagnostic. */
            error: string;
        };
        /** @description A second person's ruling on a decision that needs one. */
        LineageApprovalRequest: {
            /** @description Free text. */
            note?: string;
            /** @description The ruling. */
            verdict: components["schemas"]["LineageApprovalVerdict"];
        };
        /**
         * @description A second person's verdict.
         * @enum {string}
         */
        LineageApprovalVerdict: "approved" | "rejected";
        /**
         * @description What a decision call did.
         * @enum {string}
         */
        LineageDecisionDisposition: "recorded" | "replayed" | "dry_run_passed";
        /**
         * @description What a steward decided.
         * @enum {string}
         */
        LineageDecisionOutcome: "link" | "not_a_link" | "unsure" | "escalate";
        /** @description A steward's decision on an item. */
        LineageDecisionRequest: {
            /** @description The `evidence_etag` of the item as read. */
            evidence_etag: string;
            /** @description Free text; required when the reason is `other`. */
            note?: string;
            /** @description What was decided. */
            outcome: components["schemas"]["LineageDecisionOutcome"];
            /** @description The chosen candidate; only for `link`. */
            predecessor_pnu?: string | null;
            reason_code?: null | components["schemas"]["LineageReasonCode"];
            /** @description The decision this one replaces. */
            supersedes_decision_id?: string | null;
        };
        /** @description The result of a decision call. */
        LineageDecisionResponse: {
            decision?: null | components["schemas"]["LineageStewardDecision"];
            /** @description What the call did. */
            disposition: components["schemas"]["LineageDecisionDisposition"];
            /** @description Whether a second person must approve. */
            requires_approval: boolean;
        };
        /**
         * @description The fixed reasons a lineage-writing decision cites.
         * @enum {string}
         */
        LineageReasonCode: "building_register" | "ownership_record" | "site_survey" | "official_document" | "cadastral_map" | "other";
        /** @description One candidate predecessor the derivation found. */
        LineageReviewCandidate: {
            /** @description What the evidence was. */
            evidence_kind: string;
            /** @description Where the evidence is. */
            evidence_ref: string;
            /** @description Lineage grade. */
            grade: string;
            /** @description Whether this candidate is the link currently in effect. */
            in_effect: boolean;
            /** @description The older PNU. */
            predecessor_pnu: string;
            /** @description Lineage relation. */
            relation: string;
        };
        /** @description Who holds an item. */
        LineageReviewClaim: {
            /** @description The steward's principal id. */
            claimed_by: string;
            /**
             * Format: date-time
             * @description When the claim lapses.
             */
            expires_at: string;
        };
        /** @description A review item with its claim and decisions. */
        LineageReviewItem: {
            /** @description Candidate predecessors with their evidence. */
            candidates: components["schemas"]["LineageReviewCandidate"][];
            claim?: null | components["schemas"]["LineageReviewClaim"];
            /** @description Every decision, newest first. */
            decisions: components["schemas"]["LineageStewardDecision"][];
            /** @description Send this back with a decision; a changed value means the evidence changed. */
            evidence_etag: string;
            /** @description Stable item id. */
            item_id: string;
            /** @description Why it is on the queue. */
            status: components["schemas"]["LineageReviewStatus"];
            /** @description The parcel to decide. */
            subject_pnu: string;
        };
        /** @description A page of review items. */
        LineageReviewItemPage: {
            /** @description Items in parcel order. */
            items: components["schemas"]["LineageReviewItem"][];
            /** @description Pass as `after` for the next page; absent on the last page. */
            next_after?: string | null;
        };
        /**
         * @description Why an item is on the review queue.
         * @enum {string}
         */
        LineageReviewStatus: "needs_review" | "pending" | "sample";
        /** @description A stored decision. */
        LineageStewardDecision: {
            /** @description `approved` or `rejected`, once a second person has ruled. */
            approval?: string | null;
            /**
             * Format: date-time
             * @description When.
             */
            decided_at: string;
            /** @description The steward's principal id. */
            decided_by: string;
            /** @description Decision id. */
            decision_id: string;
            /** @description What was decided. */
            outcome: components["schemas"]["LineageDecisionOutcome"];
            /** @description The linked candidate, for a link. */
            predecessor_pnu?: string | null;
            /** @description Whether a second person must approve before it takes effect. */
            requires_approval: boolean;
            /** @description The decision this one replaces. */
            supersedes_decision_id?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    rule_on_decision: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Decision id */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LineageApprovalRequest"];
            };
        };
        responses: {
            /** @description The ruling is recorded */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LineageStewardDecision"];
                };
            };
            /** @description The decision needs no ruling or already has one */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Staff identity credential is missing or invalid */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Principal may not adjudicate, or is the decider */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Internal persistence failure */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InternalApiErrorResponse"];
                };
            };
            /** @description Identity authorization is unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_items: {
        parameters: {
            query?: {
                /** @description Only this status. */
                status?: components["schemas"]["LineageReviewStatus"];
                /** @description Only parcels whose PNU starts with these digits (a sido or sigungu code). */
                prefix?: string;
                /** @description Only items without a standing decision on their current evidence. */
                undecided_only?: boolean;
                /** @description The `next_after` of the previous page. */
                after?: string;
                /** @description Page size, at most 200. */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Review items in parcel order */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LineageReviewItemPage"];
                };
            };
            /** @description A filter is malformed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Staff identity credential is missing or invalid */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Principal may not review lineage */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal persistence failure */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InternalApiErrorResponse"];
                };
            };
            /** @description Identity authorization is unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_item: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Review item id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The item with its candidates, claim and decisions */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LineageReviewItem"];
                };
            };
            /** @description Staff identity credential is missing or invalid */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Principal may not review lineage */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No such review item */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Internal persistence failure */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InternalApiErrorResponse"];
                };
            };
            /** @description Identity authorization is unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    claim_item: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Review item id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Claimed or renewed for 30 minutes */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LineageReviewClaim"];
                };
            };
            /** @description Staff identity credential is missing or invalid */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Principal may not review lineage */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No such review item */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Another steward holds the item */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Internal persistence failure */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InternalApiErrorResponse"];
                };
            };
            /** @description Identity authorization is unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    decide_item: {
        parameters: {
            query?: {
                /** @description Run every check and store nothing. */
                dry_run?: boolean;
            };
            header?: {
                /** @description Required unless dry_run: 8-200 printable ASCII characters */
                "Idempotency-Key"?: string | null;
            };
            path: {
                /** @description Review item id */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LineageDecisionRequest"];
            };
        };
        responses: {
            /** @description Recorded, replayed, or dry run passed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LineageDecisionResponse"];
                };
            };
            /** @description The decision is malformed or names no candidate */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Staff identity credential is missing or invalid */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Principal may not review lineage */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No such review item */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Evidence changed, another steward holds the item, the key was reused with another body, or the predecessor is taken */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Internal persistence failure */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InternalApiErrorResponse"];
                };
            };
            /** @description Identity authorization is unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    release_item: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Review item id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The caller's claim, if any, is released */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Staff identity credential is missing or invalid */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Principal may not review lineage */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal persistence failure */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InternalApiErrorResponse"];
                };
            };
            /** @description Identity authorization is unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
