/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/catalog/v1/pipeline-graph": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get the Foundation Platform pipeline graph registry
         * @description Returns the provider-neutral pipeline graph contract owned by Foundation Platform.
         */
        get: operations["getPipelineGraph"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        PipelineGraphResponse: {
            /** @enum {integer} */
            schema_version: 2;
            /** Format: date-time */
            generated_at_utc: string;
            /** @enum {string} */
            owner: "foundation-platform";
            viewer_policy: components["schemas"]["PipelineGraphViewerPolicy"];
            nodes: components["schemas"]["PipelineGraphNode"][];
            edges: components["schemas"]["PipelineGraphEdge"][];
            runtime: components["schemas"]["PipelineGraphRuntime"];
        };
        PipelineGraphViewerPolicy: {
            /** @enum {string} */
            canonical_store: "foundation-platform";
            /** @enum {string} */
            ui_state_store: "product-viewer";
        };
        PipelineGraphNode: {
            id: string;
            /** @enum {string} */
            type: "source_group" | "silver_table" | "gold_table" | "reference_table" | "serving_group" | "serving_surface";
            status: string;
            /** @enum {string} */
            owner: "foundation-platform";
            title: string;
            description: string;
            runbook_ref?: string;
            blocking_reason?: string;
            target_state?: string;
            evidence_refs: string[];
            runtime_bindings?: components["schemas"]["PipelineGraphRuntimeBinding"][];
            table_name?: string;
            endpoint_catalog_group?: string;
            surface_kind?: string;
            unmapped_status?: string;
            tables?: string[];
        };
        PipelineGraphRuntimeBinding: {
            /** @enum {string} */
            kind: "ingestion_source" | "lakehouse_contract" | "outbox_scope";
            value: string;
        };
        PipelineGraphEdge: {
            id: string;
            from: string;
            to: string;
            relation: string;
            via: string[];
            status: string;
            source_slugs?: string[];
        };
        PipelineGraphRuntime: {
            database_ready: boolean;
            nodes: {
                [key: string]: components["schemas"]["PipelineGraphRuntimeNode"];
            };
        };
        PipelineGraphRuntimeNode: {
            /** @enum {string} */
            status: "healthy" | "running" | "waiting" | "stale" | "failed" | "blocked" | "manual_approval" | "missing" | "disabled" | "unknown" | "planned";
            reason: string;
            observed: {
                [key: string]: unknown;
            };
        };
        PipelineGraphErrorResponse: {
            /** @enum {string} */
            code: "pipeline_graph_registry_invalid";
            message: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getPipelineGraph: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Pipeline graph registry */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PipelineGraphResponse"];
                };
            };
            /** @description Embedded registry is invalid */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PipelineGraphErrorResponse"];
                };
            };
        };
    };
}
