//! Commands and receipts for proposal governance operations.

use foundation_normalization_domain::{
    NormalizationProposalStatus, NormalizationReviewDecision, NormalizationTargetKind,
};
use foundation_shared_kernel::ids::PrincipalId;
use serde_json::Value as JsonValue;
use uuid::Uuid;

/// Command persisted when an AI-assisted normalization proposal is submitted.
#[derive(Clone, Debug)]
pub struct NormalizationProposalSubmissionCommand {
    /// Proposal row id generated by the caller at the application boundary.
    pub id: Uuid,
    /// Idempotent proposal key computed by Foundation Platform.
    pub proposal_key: String,
    /// Service identity that submitted the proposal, usually `intelligence-platform`.
    pub submitted_by_service: String,
    /// Verified Identity Platform principal that submitted the proposal.
    pub submitted_by_principal_id: PrincipalId,
    /// System that produced or owns the raw source record.
    pub source_system: String,
    /// Stable raw record identity inside `source_system`.
    pub raw_record_id: String,
    /// Optional raw object key for lineage.
    pub raw_object_key: Option<String>,
    /// Optional lowercase SHA-256 checksum of the raw source bytes.
    pub raw_checksum_sha256: Option<String>,
    /// Optional Bronze object row id when the source is already cataloged.
    pub bronze_object_id: Option<Uuid>,
    /// Canonical fact kind targeted by the proposal.
    pub target_kind: NormalizationTargetKind,
    /// JSON object identifying the target fact.
    pub target_identity: JsonValue,
    /// Schema version expected by the target canonical fact.
    pub target_schema_version: String,
    /// Schema version of `proposed_record`.
    pub proposal_schema_version: String,
    /// Proposed normalized record payload.
    pub proposed_record: JsonValue,
    /// Lowercase SHA-256 hash of the canonicalized proposed record payload.
    pub proposed_record_sha256: String,
    /// Optional proposed JSON patch payload.
    pub proposed_patch: Option<JsonValue>,
    /// Model confidence in the inclusive range `[0, 1]`.
    pub confidence: f64,
    /// Evidence object supplied with the proposal.
    pub evidence: JsonValue,
    /// Validation object supplied with the proposal.
    pub validation: JsonValue,
    /// Optional model profile identifier used by intelligence-platform.
    pub model_profile_id: Option<String>,
    /// Optional model identifier used by intelligence-platform.
    pub model_id: Option<String>,
    /// Optional prompt identifier used by intelligence-platform.
    pub prompt_id: Option<String>,
    /// Optional prompt version used by intelligence-platform.
    pub prompt_version: Option<String>,
    /// Normalization policy identifier.
    pub policy_id: String,
    /// Normalization policy version.
    pub policy_version: String,
    /// Cross-service trace identifier.
    pub trace_id: String,
    /// Proposal lifecycle status. Submit use cases force this to `PendingReview`.
    pub status: NormalizationProposalStatus,
}

/// Result returned after a normalization proposal submit attempt.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct NormalizationProposalRecord {
    /// Durable proposal row id.
    pub id: Uuid,
    /// Idempotent proposal key computed by Foundation Platform.
    pub proposal_key: String,
    /// Current proposal lifecycle status.
    pub status: NormalizationProposalStatus,
    /// Whether this call inserted a new proposal rather than returning an existing row.
    pub created: bool,
}

/// Command persisted when an authorized principal decides a pending proposal.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct NormalizationProposalReviewCommand {
    /// Review row id generated by the caller at the application boundary.
    pub id: Uuid,
    /// Durable proposal row being reviewed.
    pub proposal_id: Uuid,
    /// Authorized principal that made the decision.
    pub reviewer_principal_id: PrincipalId,
    /// Human review decision.
    pub decision: NormalizationReviewDecision,
    /// Human-readable review reason persisted for audit.
    pub reason: String,
}

/// Command that applies an approved normalization proposal.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct NormalizationApplicationCommand {
    /// Application row id generated by the caller at the application boundary.
    pub id: Uuid,
    /// Approved proposal to apply.
    pub proposal_id: Uuid,
    /// Canonical version observed by the reviewer or operator.
    pub expected_version: i64,
    /// Authorized principal applying the reviewed proposal.
    pub applied_by_principal_id: PrincipalId,
}

/// Result returned after applying a normalization proposal.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct NormalizationApplicationRecord {
    /// Durable application row id.
    pub id: Uuid,
    /// Proposal that was applied.
    pub proposal_id: Uuid,
    /// Canonical fact kind changed by this application.
    pub target_kind: NormalizationTargetKind,
    /// Canonical target id changed by this application, when applicable.
    pub target_id: Option<Uuid>,
}

/// Command that rolls back an applied normalization application.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct NormalizationRollbackCommand {
    /// Rollback application row id generated by the caller at the application boundary.
    pub id: Uuid,
    /// Original normalization application to compensate.
    pub application_id: Uuid,
    /// Canonical version observed by the reviewer or operator before rollback.
    pub expected_current_version: i64,
    /// Human-readable rollback reason validated at the command boundary.
    ///
    /// Persistence requires the separately approved exact-retry/audit schema contract; current
    /// application rows do not store this value.
    pub reason: String,
    /// Authorized principal requesting the rollback.
    pub rolled_back_by_principal_id: PrincipalId,
}

/// Result returned after rolling back a normalization application.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct NormalizationRollbackRecord {
    /// Durable rollback application row id.
    pub id: Uuid,
    /// Original application that this row compensates.
    pub rollback_of: Uuid,
    /// Canonical fact kind changed by this rollback.
    pub target_kind: NormalizationTargetKind,
    /// Canonical target id changed by this rollback, when applicable.
    pub target_id: Option<Uuid>,
}
